<?php
  if(!$this->driver ?? null) {
    return;
  }
  if($this->driver instanceof \ThULB\RecordDriver\SolrVZGRecord && ($this->driver->isFormat('Book|eBook', true))) {
    return;
  }

  $cleanDoi = $this->driver->getCleanDOI();
  $doi = $this->doi($this->driver, $this->location ?? '');
  $doiActive = $doi->isActive();
?>
<?php if ($doiActive && ($linkedDoi = $this->dhge_doiLinker($cleanDoi))): ?>
  <?php foreach($linkedDoi[$cleanDoi] as $linkedDoiData): ?>
    <a href="<?= $linkedDoiData['link'];?>" target="_blank" class="btn btn-primary <?= $linkedDoiData['source'] ?? ''; ?>">
      <?php if($linkedDoiData['source'] == 'unpaywall'): ?>
        <div><i class="fa fa-unlock-alt"></i></div>
      <?php endif; ?>
      <?= $linkedDoiData['label'];?>
    </a><br>
  <?php endforeach; ?>
<?php endif; ?>
