<?php if($holding['items'][0]['locationapiid'] ?? false): ?>
  <?php $locationData = $this->thulb_locationData($holding['items'][0]['locationapiid']); ?>
  <?php if(!empty($locationData)): ?>
    <?php $weekday = date('N'); ?>
    <div class="location-data-wrapper">
      <div class="location-data">
        <h5><?= $this->transEsc('Address'); ?>:</h5>
        <div><?= $locationData['address']; ?></div>
        <h5><?= $this->transEsc('Phone Number'); ?>:</h5>
        <div><?= $locationData['phone']; ?></div>
        <h5><?= $this->transEsc('Opening hours'); ?>:</h5>
        <table class="mb-2">
          <?php foreach($locationData['openingHours'] as $jdday => $day): ?>
            <tr>
              <td class="pr-2 <?= ($weekday % 7) == $jdday ? 'bold' : ''; ?>"><?= $this->transEsc($day['day']); ?>:</td>
              <td class="<?= ($weekday % 7) == $jdday ? 'bold' : ''; ?>" ><?= $this->transEsc($day['formattedTime']); ?></td>
            </tr>
          <?php endforeach; ?>
        </table>
        <div class="flex flex-space-evenly">
          <a href="<?= $locationData['googleMapsUrl']; ?>" target="_blank"><i class="fa fa-map-marker"></i></a>
          <a href="<?= $holding['locationhref']; ?>" target="_blank"><i class="fa fa-cloud"></i></a>
        </div>
      </div>
    </div>
  <?php endif; ?>
<?php endif; ?>
