<?php $locationApiId = $holding['items'][0]['locationapiid'] ?? false; ?>
<?php if(in_array($locationApiId, [2, 3, 4, 8])): ?>
  <?php $locationData = $this->thulb_locationData($locationApiId); ?>
  <?php if(!empty($locationData)): ?>
    <?php $weekday = date('N'); ?>
    <div id="location-data-<?= $locationApiId; ?>" class="location-data-wrapper">
      <div class="location-data">
        <h4><?= $locationData['name']; ?></h4>

        <h5><?= $this->transEsc('Address'); ?>:</h5>
        <div class="ws-nowrap">
          <?= $locationData['address']; ?>
          <a href="<?= $locationData['googleMapsUrl']; ?>" target="_blank" data-lightbox-ignore><i class="fa fa-map-marker"></i></a>
        </div>

        <h5><?= $this->transEsc('Phone Number'); ?>:</h5>
        <div><?= $locationData['phone']; ?></div>

        <h5><?= $this->transEsc('Opening hours'); ?>:</h5>
        <table class="mb-2">
          <?php foreach($locationData['openingHours'] as $jdday => $day): ?>
            <tr>
              <td class="pr-2 <?= ($weekday % 7) == $jdday ? 'bold' : ''; ?>"><?= $this->transEsc($day['day']); ?>:</td>
              <td class="<?= ($weekday % 7) == $jdday ? 'bold' : ''; ?>" ><?= $this->transEsc($day['formattedTime']); ?></td>
            </tr>
          <?php endforeach; ?>
        </table>

        <a href="<?= $holding['locationhref']; ?>" target="_blank" data-lightbox-ignore><?= $this->transEsc('Further location information'); ?></a>
      </div>
    </div>
  <?php endif; ?>
<?php endif; ?>
