<?php if(is_callable([$this->driver, 'isFormat']) && $this->driver->isFormat('Article|electronic Article', true)): ?>
  <?php if($series = $this->driver->getSeries(false)): ?>
    <?php $firstKey = array_key_first($series); ?>
    <?= $this->transEsc('see parent work'); ?>:
    <a class="access-tab-parent-link" href="<?= $this->recordLinker()->related(['type' => 'bib', 'value' => $series[$firstKey]['id']]); ?>" target="_blank"><?= $this->escapeHtml($series[$firstKey]['name'])?></a>
    <?= $this->escapeHtml($series[$firstKey]['number'] ?? ''); ?>
  <?php endif; ?>
<?php endif; ?>
