<h2>Erklärung zur Barrierefreiheit: ThULB-Suche</h2>

<p>
  Diese Erklärung zur Barrierefreiheit gilt für die unter <a href="https://suche.thulb.uni-jena.de/">https://suche.thulb.uni-jena.de</a> veröffentlichte Website der Thüringer Universitäts- und Landesbibliothek Jena (ThULB).
  Als öffentliche Stelle im Sinne der Richtlinie (EU) 2016/2102 sind wir bemüht, unsere Websites und mobilen Anwendungen im Einklang mit den Bestimmungen des Behindertengleichstellungsgesetzes des Bundes (BGG) sowie der Barrierefreien-Informationstechnik-Verordnung (BITV 2.0) zur Umsetzung der Richtlinie (EU) 2016/2102 barrierefrei zugänglich zu machen.
</p>

<h3>Stand der Vereinbarkeit mit den Anforderungen</h3>

<p>
  Die Anforderungen der Barrierefreiheit ergeben sich aus §§ 3 Absätze 1 bis 4 und 4 der BITV 2.0, die auf der Grundlage von § 12d BGG erlassen wurde.
  Die Überprüfung der Einhaltung der Anforderungen beruht auf einer Bewertung nach den gesetzlichen Vorgaben und weltweiten Normen (EN 301 549, BITV 2.0).
  Die Überprüfung der Website ist noch nicht abgeschlossen.
  <!--Aufgrund der Überprüfung ist die Website mit den zuvor genannten Anforderungen wegen der folgenden Ausnahmen teilweise vereinbar.
  Die nachstehend aufgeführten Inhalte sind nicht barrierefrei:

  […]-->
</p>

<h3>Begründung</h3>

<p>
  Die ThULB arbeitet beständig an der Verbesserung ihres Webauftritts und konnte aufgrund der Fülle des Materials noch nicht alle Inhalte und Services digital barrierefrei gestalten. Wir sind bemüht, alle Hürden für Menschen mit Behinderung zeitnah zu beseitigen.
</p>

<h3>Datum der Erstellung</h3>

<p>
  Diese Erklärung wurde am 18.06.2025 erstellt.
</p>

<h3>Kontakt und Feedback-Möglichkeit</h3>

<p>
  Sie möchten uns bestehende Barrieren mitteilen oder Informationen zur Umsetzung der Barrierefreiheit erfragen? Dann können Sie sich gerne bei uns melden. Sie erreichen uns unter folgender Adresse:
</p>

<p>
  <span class="d-block">Friedrich-Schiller-Universität Jena</span>
  <span class="d-block">Thüringer Universitäts- und Landesbibliothek Jena</span>
  <span class="d-block">Bibliotheksplatz 2</span>
  <span class="d-block">07743 Jena</span>

  <span class="d-block">eMail: barrierefreiheit_thulb@uni-jena.de</span>
  <span class="d-block">Telefon: +49 3641 9-404000</span>
  <span class="d-block">Fax: +49 3641 9-404002</span>
</p>

<h3>Durchsetzungsverfahren</h3>

<p>
  Wenn Sie auf Mitteilungen oder Anfragen über den o.g. Kontakt für Feedback keine zufriedenstellende Antwort erhalten oder die Gründe für eine Ausnahme von der barrierefreien Gestaltung überprüfen lassen wollen, können Sie sich an die zuständige Durchsetzungsstelle wenden. Sie erreichen die Durchsetzungsstelle unter folgender Adresse:
</p>

<p>
  <span class="d-block">Thüringer Landesbeauftragter für Menschen mit Behinderungen</span>
  <span class="d-block">Landesdurchsetzungsstelle Thüringen</span>
  <span class="d-block">Häßlerstraße 6</span>
  <span class="d-block">99096 Erfurt</span>

  <span class="d-block">eMail: kontakt@tlmb.thueringen.de</span>
  <span class="d-block">Telefon: +49 361 5-73118000</span>
  <span class="d-block">Fax: +49 361 5-73118010</span>
</p>
