<h2>Barrierefreiheitserklärung: ThULB-Suche</h2>

<p>
  Die Friedrich-Schiller-Universität Jena ist bemüht, ihre Webseiten im Einklang mit den nationalen
  Rechtsvorschriften zur Umsetzung der Richtlinie (EU) 2016/2102 des Europäischen Parlaments und
  des Rates barrierefrei zugänglich zu machen.
</p>

<p>Diese Erklärung zur Barrierefreiheit gilt für <a href="https://suche.thulb.uni-jena.de/">https://suche.thulb.uni-jena.de</a>.</p>

<h3>Ergebnis der Selbstbewertung</h3>
<table class="accessibility-table">
  <tr>
    <th>Bewertung nach BITV/WCAG</th>
    <td>Ein BITV-Test für die Website wird aktuell durchgeführt.</td>
  </tr>
  <tr>
    <th>Erstellt</th>
    <td>18.06.2025</td>
  </tr>
  <tr>
    <th>Zuletzt geprüft</th>
    <td>-</td>
  </tr>
</table>

<h3>Durchsetzungsverfahren</h3>
<p>
  Sollten Sie der Ansicht sein, durch eine nicht ausreichende barrierefreie Gestaltung der Dienste des
  Universitätsrechenzentrums benachteiligt zu werden oder wenn wir Ihre Rückmeldungen nicht zu Ihrer Befriedigung
  bearbeiten, können Sie sich an die Durchsetzungsstelle nach dem ThürBarrWebG wenden:
</p>

<p>
  <span class="d-block">Landesdurchsetzungsstelle Thüringen</span>
  <span class="d-block">Kommissarische Leitung</span>
  <span class="d-block">Markus Lorenz</span>
  <span class="d-block mb-2">c/o Thüringer Landesbeauftragter für Menschen mit Behinderungen</span>

  <span class="d-block">Tel: +49 (0) 361 57 31 18 000</span>
  <span class="d-block mb-2">Fax: +49 (0) 361 57 31 18 010</span>

  <a class="d-block" href="mailto:kontakt@tlmb.thueringen.de">kontakt@tlmb.thueringen.de</a>
  <a class="d-block" href="https://www.tlmb-thueringen.de/service/ansprechpartner/landesdurchsetzungsstelle-it/">https://www.tlmb-thueringen.de/service/ansprechpartner/landesdurchsetzungsstelle-it/</a>
</p>

<h3>Feedback-Mechanismus und Kontaktangaben</h3>
<p>
  Sie können uns als Nutzer Mängel bei der Einhaltung der Anforderungen an die Barrierefreiheit mitteilen oder
  Informationen, die nicht barrierefrei dargestellt werden, barrierefrei anfordern.
</p>

<p>
  Das Discovery-Team ist dafür Ihr erster Ansprechpartner und leitet Ihre Anfrage an die zuständigen Stellen weiter.
</p>

<p>
  <span class="d-block">Discovery-Team</span>
  <a class="d-block" href="mailto:discovery_thulb@uni-jena.de">discovery_thulb@uni-jena.de</a>
</p>

<h3>Begründung</h3>
<p>
  Die Friedrich-Schiller-Universität Jena ist bemüht, alle Angebote barrierefrei zugänglich zu machen und alle aktuell
  nicht barrierefreien Inhalte nachzubessern.
</p>

<p>
  Auf Grund der technischen Struktur ist es mit der derzeit aktuellen Umsetzung jedoch nicht möglich, allen
  Anforderungen der Barrierefreiheit vollständig gerecht zu werden. Wir sind bemüht, dies zukünftig nachzubessern.
</p>
