<h2>Accessibility statement: ThULB-Suche</h2>

<p>
  Friedrich Schiller University Jena endeavours to make its websites accessible in accordance with the national
  legislation implementing Directive (EU) 2016/2102 of the European Parliament and of the Council.
</p>

<p>This accessibility statement applies to  <a href="https://suche.thulb.uni-jena.de/">https://suche.thulb.uni-jena.de</a>.</p>

<h3>Result of the self-assessment
</h3>
<table class="accessibility-table">
  <tr>
    <th>Assessment according to BITV/WCAG</th>
    <td>A BITV test is currently in progress.</td>
  </tr>
  <tr>
    <th>Created </th>
    <td>18.06.2025</td>
  </tr>
  <tr>
    <th>Last checked</th>
    <td>-</td>
  </tr>
</table>

<h3>Enforcement procedure</h3>
<p>
  If you believe that you have been disadvantaged by insufficient accessibility of the services of the University
  Computer Centre or if we do not process your feedback to your satisfaction, you can contact the enforcement
  body in accordance with the ThürBarrWebG:
</p>

<p>
  <span class="d-block">Landesdurchsetzungsstelle Thüringen</span>
  <span class="d-block">Kommissarische Leitung</span>
  <span class="d-block">Markus Lorenz</span>
  <span class="d-block mb-2">c/o Thüringer Landesbeauftragter für Menschen mit Behinderungen</span>

  <span class="d-block">Tel: +49 (0) 361 57 31 18 000</span>
  <span class="d-block mb-2">Fax: +49 (0) 361 57 31 18 010</span>

  <a class="d-block" href="mailto:kontakt@tlmb.thueringen.de">kontakt@tlmb.thueringen.de</a>
  <a class="d-block" href="https://www.tlmb-thueringen.de/service/ansprechpartner/landesdurchsetzungsstelle-it/">https://www.tlmb-thueringen.de/service/ansprechpartner/landesdurchsetzungsstelle-it/</a>
</p>

<h3>Feedback mechanism and contact details</h3>
<p>
  As a user, you can inform us of any deficiencies in compliance with accessibility requirements or request
  accessible information that is not presented in an accessible manner.
</p>

<p>
  The Discovery Team is your first point of contact and will forward your enquiry to the relevant departments.
</p>

<p>
  <span class="d-block">Discovery-Team</span>
  <a class="d-block" href="mailto:discovery_thulb@uni-jena.de">discovery_thulb@uni-jena.de</a>
</p>

<h3>Explanation</h3>
<p>
  The Friedrich Schiller University Jena endeavours to make all services accessible and to improve all content
  that is currently not accessible.
</p>

<p>
  However, due to the technical structure, it is not possible to fully fulfil all accessibility requirements with
  the current implementation. We will endeavour to improve this in the future.
</p>
