<h2>Accessibility statement: ThULB-Suche</h2>

<p>
  This accessibility statement applies to the website of the Thuringian University and State Library Jena (ThULB) published at <a href="https://suche.thulb.uni-jena.de/">https://suche.thulb.uni-jena.de</a>.
  As a public body within the meaning of Directive (EU) 2016/2102, we endeavor to make our websites and mobile applications accessible in accordance with the provisions of the Federal Disability Equality Act (BGG) and the Accessible Information Technology Ordinance (BITV 2.0) for the implementation of Directive (EU) 2016/2102.
</p>

<h3>Status of compatibility with requirements</h3>

<p>
  The accessibility requirements are set out in sections 3 (1) to (4) and 4 of BITV 2.0, which was issued on the basis of section 12d BGG.
  The review of compliance with the requirements is based on an assessment in accordance with the legal requirements and global standards (EN 301 549, BITV 2.0).
  The review of the website has not yet been completed.
  <!--Aufgrund der Überprüfung ist die Website mit den zuvor genannten Anforderungen wegen der folgenden Ausnahmen teilweise vereinbar.
  Die nachstehend aufgeführten Inhalte sind nicht barrierefrei:

  […]-->
</p>

<h3>Reason</h3>

<p>
  The ThULB is constantly working on improving its website and has not yet been able to make all content and services digitally accessible due to the wealth of material. We are endeavoring to remove all obstacles for people with disabilities as soon as possible.
</p>

<h3>Date of creation</h3>

<p>
  This declaration was created on 18.06.2025.
</p>

<h3>Contact and feedback option</h3>

<p>
  Would you like to tell us about existing barriers or ask for information on implementing accessibility? Then you are welcome to contact us. You can reach us at the following address:
</p>

<p>
  <span class="d-block">Friedrich-Schiller-Universität Jena</span>
  <span class="d-block">Thüringer Universitäts- und Landesbibliothek Jena</span>
  <span class="d-block">Bibliotheksplatz 2</span>
  <span class="d-block">07743 Jena</span>

  <span class="d-block">eMail: barrierefreiheit_thulb@uni-jena.de</span>
  <span class="d-block">Telefon: +49 3641 9-404000</span>
  <span class="d-block">Fax: +49 3641 9-404002</span>
</p>

<h3>Enforcement procedure</h3>

<p>
  If you do not receive a satisfactory response to messages or inquiries via the above feedback contact or if you wish to have the reasons for an exception to the accessibility requirement checked, you can contact the relevant enforcement body. You can reach the enforcement body at the following address:
</p>

<p>
  <span class="d-block">Thüringer Landesbeauftragter für Menschen mit Behinderungen</span>
  <span class="d-block">Landesdurchsetzungsstelle Thüringen</span>
  <span class="d-block">Häßlerstraße 6</span>
  <span class="d-block">99096 Erfurt</span>

  <span class="d-block">eMail: kontakt@tlmb.thueringen.de</span>
  <span class="d-block">Telefon: +49 361 5-73118000</span>
  <span class="d-block">Fax: +49 361 5-73118010</span>
</p>
