<?php if (isset($list)): ?>
  <input type="hidden" name="listID" value="<?=$this->escapeHtmlAttr($list->getId())?>">
  <input type="hidden" name="listName" value="<?=$this->escapeHtmlAttr($list->getTitle())?>">
<?php endif; ?>
<?php $user = $this->auth()->getUserObject(); ?>

<nav class="bulkActionButtons d-flex ms-2 gap-3 justify-content-between">
  <?php
  $socialConfig = $this->config()->get('config')['Social'];
  $multiPageSelection = $socialConfig['multi_page_favorites_selection'] ?? true;
  $checkboxSelectAllType = $socialConfig['checkbox_select_all_favorites_type'] ?? 'both';
  ?>

  <ul class="selection-controls-bar d-flex flex-column align-items-start">
    <?php if(in_array($checkboxSelectAllType, ['on_page', 'both'])): ?>
      <li class="bulk-checkbox">
        <input type="checkbox" name="selectAll" class="checkbox-select-all" id="myresearchCheckAll">
        <label for="myresearchCheckAll"><?=$this->transEsc('select_all_on_page')?></label>
      </li>
    <?php endif; ?>

    <?php if($multiPageSelection && in_array($checkboxSelectAllType, ['global', 'both'])): ?>
      <li class="bulk-checkbox">
        <div class="select-all-global hidden">
          <input type="checkbox" name="selectAllGlobal" class="checkbox-select-all-global" id="myresearchCheckAllGlobal">
          <label for="myresearchCheckAllGlobal"><?=$this->transEsc('select_all')?></label>
        </div>
      </li>
    <?php endif; ?>

    <?php if($multiPageSelection): ?>
      <li>
        <button type="button" class="clear-selection hidden"></button>
      </li>
    <?php endif; ?>
  </ul>

  <div class="item-count">
    <?php $recordTotal = $this->results->getResultTotal(); ?>
    <?php if ($recordTotal > 0): ?>
      <?php
        $transParams = [
          '%%start%%' => $this->localizedNumber($this->results->getStartRecord()),
          '%%end%%' => $this->localizedNumber($this->results->getEndRecord()),
          '%%total%%' => $this->localizedNumber($recordTotal)
        ];
      ?>
      <?= $this->translate('showing_items_of_html', $transParams); ?>
    <?php endif; ?>
  </div>

  <div class="btn-group">
    <a class="btn btn-thulb visible-xs dropdown-toggle" data-toggle="dropdown"><i class="fa fa-ellipsis-v" aria-hidden="true"></i></a>
    <div class="dropdown-menu dropdown-menu-right" id="list-actions">
      <ul class="action-toolbar">
      <?= $this->bulkAction()->button('email', 'send-email', 'bulk_email_myresearch', [
        'title' => $this->translate('bulk_email_myresearch'),
      ]) ?>

      <?php if ((null !== $this->list && $this->list->editAllowed($user)) || null === $this->list && $user): ?>
        <?= $this->bulkAction()->button('delete', 'ui-delete', 'bulk_delete_myresearch', [
          'id' => $this->idPrefix . 'delete_list_items_' . (null !== $this->list ? $this->escapeHtmlAttr($this->list->getId()) : ''),
          'title' => $this->translate('bulk_delete_myresearch'),
        ]) ?>
      <?php endif; ?>

      <?php $exportOptions = $this->export()->getActiveFormats('bulk'); ?>
      <?php if (count($exportOptions) > 0): ?>
        <?= $this->bulkAction()->button('export', 'export', 'bulk_export_myresearch', [
          'title' => $this->translate('bulk_export_myresearch'),
        ]) ?>
      <?php endif; ?>

      <?= $this->bulkAction()->button('print', 'print', 'bulk_print_myresearch', [
        'title' => $this->translate('bulk_print_myresearch'),
        'data-lightbox-ignore' => '',
      ]) ?>

      <?php if ($this->cart()->isActive()): ?>
        <?= $this->bulkAction()->button('add', 'cart-add', 'Add to Book Bag', [
          'id' => $this->idPrefix . 'updateCart',
          'title' => $this->translate('Add to Book Bag'),
        ]) ?>
      <?php endif; ?>
      </ul>
    </div>
  </div>
</nav>
