<?php
  // Set up page title:
  $this->headTitle($this->translate('Change Password'));

  // Disable breadcrumbs:
  $this->layout()->breadcrumbs = false;
?>

<?php if (!$this->inLightbox && $this->auth()->getUserObject() && !$this->forced): ?>
  <?=$this->component('show-account-menu-button')?>
  <div class="<?=$this->layoutClass('mainbody')?>">
<?php endif; ?>

<h2><?=$this->transEsc('Change Password') ?></h2>
<?=$this->flashmessages() ?>


<?php if (!$this->auth()->getManager()->supportsPasswordChange($this->auth_method)): ?>
  <div class="error"><?=$this->transEsc('recovery_new_disabled') ?></div>
<?php elseif (!isset($this->hash)): ?>
  <div class="error"><?=$this->transEsc('recovery_user_not_found') ?></div>
<?php else: ?>
  <form id="newpassword" class="form-new-password" action="<?=$this->url('myresearch-newpassword') ?>" method="post" data-toggle="validator">
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->auth()->getManager()->getCsrfHash())?>" name="csrf">
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->hash) ?>" name="hash">
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->username) ?>" name="username">
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->auth_method) ?>" name="auth_method">
    <?=$this->auth()->getNewPasswordForm() ?>
    <?=$this->captcha()->html($this->useCaptcha) ?>
    <div class="form-group">
      <input class="btn btn-primary" name="submitButton" type="submit" value="<?=$this->transEscAttr('Submit')?>" />
    </div>
  </form>
<?php endif; ?>

<?php if (!$this->inLightbox && $this->auth()->getUserObject() && !$this->forced): ?>
  </div>
  <div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar" role="navigation" aria-label="<?=$this->transEsc('account_menu_label')?>">
    <?=$this->accountMenu()->render('changepassword')?>
  </div>
<?php endif; ?>
