<?php $account = $this->auth()->getManager(); ?>
<?php $sessionInitiator = $account->getSessionInitiator($this->serverUrl($this->url('myresearch-home'))); ?>
<?php if (!$sessionInitiator): // display default login form if no login URL provided ?>
  <form method="post" action="<?=$this->url('myresearch-home')?>" name="loginForm" class="form-login">
    <?=$this->auth()->getLoginFields()?>
    <?php if ($account->supportsPersistentLogin()) : ?>
      <div class="form-group">
        <label>
          <input type="checkbox" name="remember_me"<?=$this->request->get('remember_me') ? ' checked' : ''?>>
          <?=$this->transEsc('remember_me', ['%%days%%' => $account->getPersistentLoginLifetime()])?>
        </label>
      </div>
    <?php endif; ?>

    <input type="hidden" name="auth_method" value="<?=$this->escapeHtmlAttr($account->getAuthMethod())?>">
    <input type="hidden" name="csrf" value="<?=$this->escapeHtmlAttr($account->getCsrfHash())?>">
    <div class="form-group flex-group flex-baseline">
      <input class="btn btn-primary mr-2 mb-2" type="submit" name="processLogin" value="<?=$this->transEscAttr('Login')?>">
      <?php if ($account->supportsCreation()): ?>
        <a class="btn btn-link createAccountLink" href="<?=$this->url('myresearch-account') ?>?auth_method=<?=$account->getAuthMethod()?>"><?=$this->transEsc('Create New Account')?></a>
      <?php endif; ?>
      <div class="mt-2">
        <?=$this->transEsc('Forgot Password')?>
        (<a href="<?=$this->transEscAttr('URL::Forgot Password Eisenach')?>" target="_blank">Eisenach <?=$this->icon('external-link')?></a>
        /
        <a href="<?=$this->transEscAttr('URL::Forgot Password Gera')?>" target="_blank">Gera <?=$this->icon('external-link')?></a>)
      </div>
    </div>
  </form>
<?php else: ?>
  <a href="<?=$this->escapeHtmlAttr($sessionInitiator)?>" class="btn btn-link" data-lightbox-ignore><?=$this->transEsc("Institutional Login")?></a>
<?php endif; ?>
