<?php $account = $this->auth()->getManager(); ?>
<?php $sessionInitiator = $account->getSessionInitiator($this->serverUrl($this->url('myresearch-home'))); ?>
<?php if (!$sessionInitiator): // display default login form if no login URL provided ?>
  <form method="post" action="<?=$this->url('myresearch-home')?>" name="loginForm" class="form-login">
    <?=$this->auth()->getLoginFields()?>
    <input type="hidden" name="auth_method" value="<?=$account->getAuthMethod()?>">
    <input type="hidden" name="csrf" value="<?=$this->escapeHtmlAttr($account->getCsrfHash())?>" />
    <div class="form-group flex-group flex-baseline">
      <input class="btn btn-primary mr-2 mb-2" type="submit" name="processLogin" value="<?=$this->transEsc('Login')?>">
      <?php if ($account->supportsCreation()): ?>
        <a class="btn btn-link createAccountLink" href="<?=$this->url('myresearch-account') ?>?auth_method=<?=$account->getAuthMethod()?>"><?=$this->transEsc('Create New Account')?></a>
      <?php endif; ?>
      <div class="mt-2">
        <?=$this->transEsc('Forgot Password')?>
        (
        <a class="external-link" href="https://kataloge.thulb.uni-jena.de/LBS_WEB/borrower/forgottenpassword/request.htm?USR=1000&BES=5&LAN=DU" target="_blank">Eisenach</a>
        /
        <a class="external-link" href="https://kataloge.thulb.uni-jena.de/LBS_WEB/borrower/forgottenpassword/request.htm?USR=1000&BES=4&LAN=DU" target="_blank">Gera</a>
        )
      </div>
    </div>
  </form>
<?php else: ?>
  <a href="<?=$this->escapeHtmlAttr($sessionInitiator)?>" class="btn btn-link" data-lightbox-ignore><?=$this->transEsc("Institutional Login")?></a>
<?php endif; ?>
