<?php $this->layout()->searchbox = false; ?>
<div class="<?=$this->layoutClass('mainbody')?>">
  <?php echo $this->flashmessages(); ?>

  <form action="<?= $this->url('Userdata-reassign'); ?>" method="post">
    <table>
      <tbody>
        <tr>
          <td class="tag-col pt-2"><?= $this->transEsc('Old Username'); ?></td>
          <td class="text-col pt-2">
            <input type="text" name="oldUserNumber" value="<?= $oldUserNumber; ?>" />
          </td>
        </tr>
        <tr>
          <td class="tag-co pt-2l"><?= $this->transEsc('New Username'); ?></td>
          <td class="text-col pt-2">
            <input type="text" name="newUserNumber" value="<?= $newUserNumber; ?>" />
          </td>
        </tr>
        <tr>
          <td class="tag-col pt-2">&nbsp;</td>
          <td class="text-col pt-2">
            <input type="submit" value="Prüfen" class="btn btn-primary"/>
          </td>
        </tr>
      </tbody>
    </table>
  </form>

  <?php if(!empty($checkData)): ?>
  <div class="dataCheck">
      <?php $userDataToDisplay = ['username' => 'Username', 'firstname' => 'First Name', 'lastname' => 'Last Name', 'email' => 'Email']; ?>
    <h2><?= $this->transEsc('Data to change'); ?>:</h2>

    <h4><?= $this->transEsc('User data'); ?></h4>
    <table>
      <thead>
        <tr class="bold">
          <td>&nbsp;</td>
          <td><?= $this->transEsc('Old User'); ?></td>
          <td><?= $this->transEsc('New User'); ?></td>
        </tr>
      </thead>
      <tbody>
      <?php foreach($userDataToDisplay as $field => $desc): ?>
        <tr>
          <td class="bold"><?= $this->transEsc($desc);?>:</td>
          <td><?= $checkData['oldUser'][$field]; ?></td>
          <?php if($checkData['newUser']['id'] ?? false): ?>
            <td><?= $checkData['newUser'][$field]; ?></td>
          <?php elseif($field == 'username'): ?>
            <td><span class="alert"><?= $this->transEsc('User not in database'); ?></span></td>
          <?php else: ?>
            <td>&nbsp;</td>
          <?php endif;; ?>
        </tr>
      <?php endforeach; ?>
      </tbody>
    </table>

    <?php if(!empty($comments = $checkData['comments'])): ?>
      <h4><?= $this->transEsc('Comments');?> (<?= count($comments); ?>):</h4>
      <table>
        <thead>
          <tr>
            <td><?= $this->transEsc('title');?></td>
            <td><?= $this->transEsc('comment');?></td>
          </tr>
        </thead>
        <tbody>
          <?php foreach($comments as $comment): ?>
            <tr>
              <td><?= $comment['record_id']; ?></td>
              <td><?= $comment['comment']; ?></td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    <?php endif; ?>

    <!-- Unvollständig -->
    <?php if(!empty($resourceTags = $checkData['resourcetags'])): ?>
      <h4><?= $this->transEsc('Tags');?> (<?= count($resourceTags); ?>):</h4>
    <?php endif; ?>

    <?php if(!empty($searches = $checkData['search'])): ?>
      <h4><?= $this->transEsc('history_saved_searches');?> (<?= count($searches); ?>):</h4>
      <table>
        <thead>
          <tr>
            <td><?= $this->transEsc('Index');?></td>
            <td><?= $this->transEsc('Search string');?></td>
          </tr>
        </thead>
        <?php foreach($searches as $search): ?>
          <tr>
            <td><?= $search['searchClass']; ?></td>
            <td><?= $search['queryString']; ?></td>
          </tr>
        <?php endforeach; ?>
      </table>
    <?php endif; ?>

    <?php if(!empty($userCards = $checkData['usercard'])): ?>
      <h4><?= $this->transEsc('User cards');?> (<?= count($userCards); ?>):</h4>
      <table>
        <thead>
          <tr>
            <td><?= $this->transEsc('Card name');?></td>
            <td><?= $this->transEsc('library');?></td>
            <td><?= $this->transEsc('Username');?></td>
          </tr>
        </thead>
        <tbody>
          <?php foreach($userCards as $userCard): ?>
            <tr>
              <td><?= $userCard['card_name']; ?></td>
              <td><?= $userCard['home_library']; ?></td>
              <td><?= $userCard['cat_username']; ?></td>
            </tr>
          <?php endforeach; ?>
          </tbody>
      </table>
    <?php endif; ?>

    <?php if(!empty($userLists = $checkData['userlist'])): ?>
      <h4><?= $this->transEsc('Favorite lists');?> (<?= count($userLists); ?>):</h4>
      <table>
        <thead>
          <tr>
            <td><?= $this->transEsc('Name');?></td>
            <td><?= $this->transEsc('Description');?></td>
            <td><?= $this->transEsc('Entries');?></td>
            <td><?= $this->transEsc('Public');?></td>
          </tr>
        </thead>
        <tbody>
          <?php foreach($userLists as $list): ?>
            <tr>
              <td><?= $list['title']; ?></td>
              <td><?= $list['description'] ?? ''; ?></td>
              <td><?= $list['entries'] ?? 0; ?></td>
              <td><?= $list['public'] ? 'Ja' : 'Nein'; ?></td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    <?php endif; ?>

    <?php if(!empty($userResources = $checkData['userresource'])): ?>
      <h4><?= $this->transEsc('Favorites');?> (<?= count($userResources); ?>):</h4>
      <table>
        <thead>
          <tr>
            <td><?= $this->transEsc('List');?></td>
            <td><?= $this->transEsc('Resource');?></td>
          </tr>
        </thead>
        <?php foreach($userResources as $resource): ?>
          <tr>
            <td><?= $resource['list_title']; ?></td>
            <td><?= $resource['record_id']; ?></td>
          </tr>
        <?php endforeach; ?>
      </table>
    <?php endif; ?>

    <form action="<?= $this->url('Userdata-save'); ?>" method="post" class="pt-2">
      <input type="hidden" name="oldUserNumber" value="<?= $oldUserNumber; ?>">
      <input type="hidden" name="newUserNumber" value="<?= $newUserNumber; ?>">
      <input type="submit" value="<?= $this->transEsc('Save'); ?>" class="btn btn-primary" />
    </form>
  </div>
  <?php endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>">
  <?=$this->render("admin/menu.phtml")?>
</div>