<?php $version = $this->config()->get('config')->Site->generator ?>
<?php preg_match("/with thulb_(.*?) build on/", $version, $versionstring) ?>
<footer class="hidden-print">
  <nav class="mt-5">
    <div class="container">
      <ul class="nav navbar-nav">
        <li><a class="p-3" href="<?= $this->translate('URL::imprint'); ?>" target="_blank"><?= $this->transEsc('Footer_imprint')?></a></li>

        <li><a class="p-3" href="https://github.com/clecle/ThULB-Suche/blob/master/CHANGELOG.md" target="_blank" title="Änderungen auf GitHub einsehen">ThULB-Suche Version <?=$versionstring[1] ?? "unknown (you are probably on TEST or DEV)" ?></a></li>

        <?php if($this->thulb_serverType() == 'development'): ?>
          <li><a class="p-3" href="<?= $this->config()->get('config.staging')->Site->url . $_SERVER['REQUEST_URI']; ?>" target="_blank">Im Testsystem öffnen</a></li>
        <?php endif; ?>

        <?php if($this->thulb_serverType() != 'production'): ?>
          <li><a class="p-3" href="<?= $this->config()->get('config.production')->Site->url . $_SERVER['REQUEST_URI']; ?>" target="_blank">Im Livesystem öffnen</a></li>
        <?php endif; ?>
      </ul>
    </div>
  </nav>
</footer>