<?php $comments = $this->thulb_holdingHelper()->getHoldingComments($holding); ?>
<?php if (!empty($comments)) : ?>
  <div class="item-notes">
    <?php if (is_array($comments) && count($comments) > 0): ?>
      <ul>
        <?php foreach ($comments as $comment): ?>
          <?php if (!empty($comment)): ?>
            <li><?= $comment ?></li>
          <?php endif; ?>
        <?php endforeach; ?>
      </ul>
    <?php endif; ?>
  </div>
<?php endif; ?>