<?php /* BESTANDSANGABEN */ ?>
<?php $chron = $this->thulb_holdingHelper()->getHoldingChronology($holding); ?>
<?php if (!empty($chron)) : ?>
  <div class="item-notes">
    <?php if (is_array($chron) && count($chron) > 0): ?>
      <?php foreach ($chron as $chron): ?>
        <?php if (!empty($chron)): ?>
          <?= $chron ?><br>
        <?php endif; ?>
      <?php endforeach; ?>
    <?php endif; ?>
  </div>
<?php endif; ?>