<div class="location">
  <h3 class="flex flex-wrap-xs">
    <span class="col-description"><?= $this->transEsc('Location') ?>:</span>
    <span class="col-text"><?= $this->thulb_holdingHelper()->getLocation($holding, true);?></span>
    <?php $locationApiId = $holding['items'][0]['locationapiid'] ?? false; ?>
    <?php if(in_array($locationApiId, [2, 3, 4, 8])): ?>
      <button class="btn btn-xs btn-primary btn-opening-hours" onclick="VuFind.lightbox.render($('#location-data-<?= $locationApiId; ?>').html());"><?= $this->transEsc('Opening hours'); ?></button>
    <?php endif; ?>
  </h3>
  <div class="flex flex-wrap-reverse-xs">
    <div class="striped flex-grow" aria-details="<?= $this->transEscAttr('Holdings details from')?> <?= $this->transEscAttr($holding['location'])?>">
      <?php if (isset($holding['textfields'])): foreach ($holding['textfields'] as $textFieldName => $textFields): ?>
        <div class="row mr-0 ml-0">
          <div class="flex flex-wrap-xs pb-1 pl-1 pr-2">
            <?php // Translation for summary is a special case for backwards-compatibility ?>
            <div class="col-description bold"><?= $textFieldName == 'summary' ? $this->transEsc("Volume Holdings") : $this->transEsc(ucfirst($textFieldName))?>:</div>
            <div class="col-text">
              <?php foreach ($textFields as $current): ?>
                <?= $this->escapeHtml($current)?><br/>
              <?php endforeach; ?>
            </div>
          </div>
        </div>
      <?php endforeach; endif; ?>

      <?php foreach ($holding['items'] as $item): ?>
        <?= $this->render('RecordTab/access/physicalHoldingItem.phtml', ['holding' => $holding, 'driver' => $driver, 'item' => $item]); ?>
      <?php endforeach; ?>

      <?php if (!empty($holding['purchase_history'])): ?>
        <div class="flex flex-wrap-xs pb-1 pl-1 pr-2">
          <div class="col-description bold"><?= $this->transEsc("Most Recent Received Issues")?>:</div>
          <div class="col-text">
            <?php foreach ($holding['purchase_history'] as $current): ?>
              <?= $this->escapeHtml($current['issue'])?><br/>
            <?php endforeach; ?>
          </div>
        </div>
      <?php endif; ?>
    </div>
  </div>
</div>