<?php
  // Set up page title:
  $this->headTitle($this->translate('ill_charge_credits'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('ill_charge_credits') . '</li>';

  $this->headScript()->appendScript(<<<JS
    function calculatePrice() {
      $('#chargeCost').html(
          new Intl.NumberFormat("de-DE", { style: "currency", currency: "EUR" }).format(
              $('#chargeQuantity').val() * $this->creditPrice
      ))
    };
  JS);
?>

<div class="<?= $this->layoutClass('mainbody'); ?> ill-charge">
  <?php if(!isset($this->exception)): ?>
    <h2><?= $this->transEsc('ill_charge_credits')?></h2>
    <?= $this->flashmessages(); ?>

    <form action="/ILL/chargeconfirmation" method="post" class="form-inline" data-lightbox>
      <?php if(!$this->hasIllAccount): ?>
        <div class="alert alert-warning"><?= $this->translate('ill_new_account_request'); ?></div>
      <?php endif; ?>

      <div class="flex-group">
        <div class="col-ill-description"><?= $this->transEsc('ill_current_credits'); ?>:</div>
        <div class="col-ill-text"><?= $this->oldQuantity; ?></div>
      </div>

      <div class="flex-group">
        <div class="col-ill-description"><?= $this->transEsc('ill_charge_credits'); ?>:</div>
        <div class="col-ill-text">
          <input type="number" id="chargeQuantity" name="chargeQuantity" oninput="calculatePrice()" value="1" min="1" max="<?= $this->chargeQuantityLimit; ?>"/>
        </div>
      </div>

      <div class="flex-group">
        <div class="col-ill-description"><?= $this->transEsc('Total'); ?>:</div>
        <div class="col-ill-text">
          <span id="chargeCost"><?= $this->safeMoneyFormat(1 * $this->creditPrice); ?></span>
        </div>
      </div>

      <p class="flex-center center-text"><?= $this->transEsc('ill_no_refund'); ?></p>

      <?php if(!$this->hasIllAccount): ?>
        <div class="ill-consent">
          <input type="checkbox" id="consent" name="consent" value="true" required />
          <label for="consent" class="font-weight-default"><?= $this->transEsc('ill_account_consent'); ?></label>
        </div>
      <?php endif; ?>

      <?php if(in_array($this->thulb_userType(), [3, 4, 6, 8])): ?>
        <div class="m-auto">
          <div class="flex-group mb-2 mt-2">
            <input type="checkbox" id="workrelated" name="workrelated" class="mr-2" value="true" />
            <label for="workrelated" class="control-label"><?= $this->transEsc('ill_work_related'); ?></label>
          </div>
          <div class="flex-group">
            <input type="text" class="form-control mr-2" name="facility" placeholder="<?= $this->transEsc('ill_work_related_facility'); ?>" />
            <input type="text" class="form-control" name="department" placeholder="<?= $this->transEsc('ill_work_related_department'); ?>" />
          </div>
        </div>
      <?php endif; ?>

      <div class="flex-center center-text">
        <button class="btn btn-primary mt-2" ><?= $this->transEsc('ill_charge_credits'); ?></button>
      </div>
    </form>
  <?php else: ?>
    <?= $this->render('error/index.phtml'); ?>
  <?php endif; ?>
</div>

<div class="<?= $this->layoutClass('sidebar')?>">
  <?= $this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'chargecredits'])?>
</div>