<div>
  <h2 class="m-auto"><?= $this->translate('ill_delete_account_confirmation'); ?></h2>
  <?= $this->flashmessages(); ?>

  <form href="/ILL/deleteaccountconfirmation" method="post">
    <input type="hidden" name="csrf" value="<?= $this->auth()->getManager()->getCsrfHash(); ?>" />
    <input type="hidden" name="confirmation" value="true" />

    <button class="btn btn-primary display-block m-auto mt-2" type="submit"><?= $this->transEsc('ill_delete_account'); ?></button>
  </form>
</div>
