<?php
// Set up page title:
$this->headTitle($this->translate('ill_delete_account'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Delete account') . '</li>';
?>
<div class="<?= $this->layoutClass('mainbody')?>">
  <h2><?= $this->transEsc('ill_delete_account')?></h2>
  <?= $this->flashmessages()?>

  <p><?= $this->transEsc('ill_delete_account_dsgvo'); ?></p>
  <form href="/ILL/deleteaccount" method="post">
    <input type="hidden" name="csrf" value="<?= $this->auth()->getManager()->getCsrfHash(); ?>" />

    <input class="btn btn-primary" type="submit" value="<?= $this->transEsc('ill_delete_account'); ?>" />
  </form>
</div>

<div class="<?= $this->layoutClass('sidebar')?>">
    <?= $this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'deleteaccount'])?>
</div>