<?php
// Set up page title:
$this->headTitle($this->translate('ill_forgot_password'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('ill_forgot_password') . '</li>';
?>
<div class="<?= $this->layoutClass('mainbody')?>">
  <h2><?= $this->transEsc('ill_forgot_password')?></h2>
  <?= $this->flashmessages()?>

  <div class="flex flex-wrap-reverse flex-gap-2 ill-forgot-password">
    <div class="mt-3 mt-0-xs">
      <p><?= $this->translate('ill_forgot_password_info'); ?></p>
      <form href="/ILL/forgotpassword" method="post">
        <input type="hidden" name="csrf" value="<?= $this->auth()->getManager()->getCsrfHash(); ?>" />
        <input class="btn btn-primary" type="submit" name="forgot-password" value="<?= $this->transEsc('ill_forgot_password_reset'); ?>" />
      </form>
    </div>

    <div class="flex-break-sm"></div>

    <div class="alert alert-warning">
      <?= $this->translate('ill_forgot_password_warning'); ?>
    </div>
  </div>
</div>

<div class="<?= $this->layoutClass('sidebar')?>">
  <?= $this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'forgotillpassword'])?>
</div>