<?php
// Set up page title:
$this->headTitle($this->translate('Forgot password'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Forgot password') . '</li>';
?>
<div class="<?= $this->layoutClass('mainbody')?>">
    <h2><?= $this->transEsc('Forgot Password')?></h2>
    <?= $this->flashmessages()?>

  <div class="alert alert-warning">
    <?= $this->translate('ill_forgot_password_warning'); ?>
  </div>
  <p>
    <?= $this->translate('ill_forgot_password_info'); ?>
  </p>
  <form href="/ILL/forgotpassword" method="post">
    <input type="hidden" name="csrf" value="<?= $this->auth()->getManager()->getCsrfHash(); ?>" />

    <input class="btn btn-primary" type="submit" value="<?= $this->transEsc(''); ?>" />
  </form>
</div>

<div class="<?= $this->layoutClass('sidebar')?>">
    <?= $this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'forgotpassword'])?>
</div>