<?php
  $js = <<<JS
    $(this).toggleClass('fa-angle-down fa-angle-up');
    $(this).next().slideToggle('slow');
  JS;
?>
<?php $summonResult = $this->recommend->getResults(); ?>
<?php if (!empty($summonResult['best_bets'])): ?>
<div class="authorbox">
  <?php foreach ($summonResult['best_bets'] as $current): ?>
    <div>
      <?php if (!empty($current['link'])): ?>
        <a class="fw-bold" href="<?= $this->escapeHtmlAttr($current['link']) ?>"><?= $this->escapeHtml($current['title']) ?></a>
      <?php else: ?>
        <b><?= $this->escapeHtml($current['title']) ?></b>
      <?php endif; ?>
      <i class="fa fa-angle-down visible-xs pull-right" onclick="<?= $js; ?>"></i>
      <div class="flex-hidden-xs"><?= $current['description'] ?></div>
    </div>
  <?php endforeach; ?>
</div>
<?php endif; ?>

<?php if (!empty($summonResult['databases'])): ?>
<div class="authorbox hidden-xs">
  <p><?= $this->transEsc('summon_database_recommendations') ?></p>
  <?php foreach ($summonResult['databases'] as $current): ?>
    <p><a href="<?= $this->escapeHtmlAttr($current['link']) ?>"><?= $this->escapeHtml($current['title']) ?></a><br/><?= $this->escapeHtml($current['description']) ?></p>
  <?php endforeach; ?>
</div>
<?php endif; ?>
