<?php
  // Set page title.
  $this->headTitle($this->translate($this->tab->getDescription()) . ': ' . $this->driver->getBreadcrumb());

  // Get search results
  try {
    $results = $this->tab->getResults();
    $params = $this->tab->getParams();
  }
  catch (\Exception $ex) {
    $results = false;
    $params = false;
  }
  $searchDetails = ['results' => $results, 'params' => $params, 'indexStart' => 1];
?>
<?php if ($results && $params && ($recordTotal = $results->getResultTotal()) > 0): // only display these at very top if we have results ?>
  <?php foreach ($results->getRecommendations('top') as $current): ?>
    <?=$this->recommend($current)?>
  <?php endforeach; ?>

  <div class="collection-list-controls align-items-md-center align-items-stretch d-flex flex-column flex-md-row gap-2 justify-content-between mx-3 my-2">
    <?php
      $transParams = [
        '%%start%%' => $this->localizedNumber($results->getStartRecord()),
        '%%end%%'   => $this->localizedNumber($results->getEndRecord()),
        '%%total%%' => $this->localizedNumber($recordTotal)
      ];
    ?>
    <div class="collection-control item-count">
      <?php if (!isset($this->skipTotalCount)): ?>
        <?=$this->translate('showing_items_of_html', $transParams); ?>
      <?php else: ?>
        <?=$this->translate('showing_items_html', $transParams); ?>
      <?php endif; ?>
    </div>

    <div class="collection-control sort order-md-first">
      <?= $this->render('search/controls/limit.phtml', $searchDetails)?>
      <?= $this->render('search/controls/sort.phtml', $searchDetails)?>
    </div>

    <div class="collection-control journal-not-found">
      <?php if($this->permission()->allowDisplay('access.JournalRequest') &&
               $this->driver->isFormat('Journal') && $this->driver->isInArchive()): ?>
        <span><?= $this->transEsc('storage_retrieval_request_volume_not_listed'); ?></span>
        <strong>
          <a href="<?= $this->url('request-journal', ['id' => $this->driver->getUniqueId()]); ?>" data-lightbox><?= $this->transEsc('storage_retrieval_request_order_here');?></a>
        </strong>
      <?php endif; ?>
    </div>
  </div>

  <div class="collection-list-results">
    <form class="form-inline" method="post" name="bulkActionForm" action="<?= $this->url('cart-searchresultsbulk')?>">
      <?=$this->context($this)->renderInContext('search/bulk-action-buttons.phtml', $searchDetails + ['idPrefix' => ''])?>
      <?=$this->render('search/list-' . $results->getParams()->getView() . '.phtml', $searchDetails)?>
      <?=$this->paginationControl($results->getPaginator(), 'Sliding', 'search/pagination.phtml', ['results' => $results, 'ajaxTab' => true])?>
    </form>
  </div>
<?php elseif($this->permission()->allowDisplay('access.JournalRequest') &&
    $this->driver->isFormat('Journal') && $this->driver->isInArchive()): ?>
  <div class="collection-list-results">
    <div class="journal-not-found">
      <span><?= $this->transEsc('storage_retrieval_request_volume_not_listed'); ?></span>
      <strong>
        <a href="<?= $this->url('request-journal', ['id' => $this->driver->getUniqueId()]); ?>" data-lightbox><?= $this->transEsc('storage_retrieval_request_order_here');?></a>
      </strong>
    </div>
  </div>
<?php endif; ?>