<h2><?= $this->transEsc('VPN not active'); ?></h2>

<p><strong><?= $this->transEsc('vpn_thulb_related_people'); ?></strong></p>

<p><?= $this->translate('vpn_thulb_related_people_text', ['%%servicedesk%%' => $serviceDeskUrl]); ?></p>

<p><strong><?= $this->transEsc('vpn_thulb_unrelated_people'); ?></strong></p>

<p><?= $this->translate('vpn_thulb_unrelated_people_text'); ?></p>

<p><?= $this->translate('vpn_thulb_further_information'); ?></p>
