<?php
  $pattern = '';
  if (isset($this->passwordPolicy['pattern'])) {
    if ($this->passwordPolicy['pattern'] == 'numeric') {
      $pattern = '\d+';
    }
    elseif ($this->passwordPolicy['pattern'] == 'alphanumeric') {
      $pattern = '[\da-zA-Z]+';
    }
    else {
      $pattern = $this->passwordPolicy['pattern'];
    }
  }
?>

<?php if (isset($this->username)): ?>
  <div class="form-group">
    <label class="control-label fw-bold"><?=$this->transEsc('Username') ?>:</label>
    <p class="form-control-static"><?=$this->username ?></p>
  </div>
<?php endif; ?>

<?php if (isset($this->verifyold) && $this->verifyold || isset($this->oldpwd)): ?>
  <div class="form-group">
    <label class="control-label fw-bold" for="oldpwd"><?=$this->transEsc('old_password') ?>:</label>
    <input type="password" name="oldpwd" id="oldpwd" class="form-control" autocomplete="current-password">
  </div>
<?php endif; ?>

<div class="form-group">
  <label class="control-label fw-bold" for="password"><?=$this->transEsc('new_password') ?>:</label>
  <?php if ($hint = $this->passwordPolicy['hint'] ?? null): ?>
    <div class="help-block"><?=$this->transEsc($hint) ?></div>
  <?php endif; ?>

  <?php
    $attrs = $this->htmlAttributes($this->passwordPolicy['inputAttrs'] ?? []);
    $attrs->merge([
      'id' => 'password',
      'type' => 'password',
      'name' => 'password',
      'class' => 'form-control',
      'autocomplete' => 'new-password',
      'aria-required' => 'true',
    ]);

    if($attrs['data-minlength'] ?? false) {
      $attrs['data-minlength-error'] = ($this->transEsc('password_minimum_length', ['%%minlength%%' => $this->passwordPolicy['minLength']]));
    }
    if($pattern) {
        $attrs->merge([
          'pattern' => $pattern,
          'oninvalid' => 'this.setCustomValidity(\'' . $this->transEsc('password_validation_error_message') . '\')"',
          'oninput' => 'this.setCustomValidity(\'\')"'
        ]);
    }
  ?>
  <input <?=$attrs?> required>
</div>
<div class="form-group">
  <label class="control-label fw-bold" for="password2"><?=$this->transEsc('confirm_new_password') ?>:</label>
  <input type="password" name="password2" id="password2" class="form-control" required aria-required="true" data-match="#password" data-match-error="<?=$this->transEscAttr('Passwords do not match')?>" autocomplete="new-password">
</div>
