<div class="collapse navbar-collapse" id="tsnavbar">
  <ul class="nav navbar-nav">
    <?php if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
      <li class="language dropdown visible-xs">
        <a href="#_" class="dropdown-toggle" data-toggle="dropdown">
          <?= strtoupper($this->layout()->userLang); ?> <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <?php foreach ($this->layout()->allLangs as $langCode => $langName): ?>
            <?php if ($this->layout()->userLang != $langCode): ?>
              <li  class="langOption"><a href="#" onClick="document.langForm.mylang.value='<?= $langCode?>';document.langForm.submit()"><?= $this->displayLanguageOption($langName)?></a></li>
            <?php else: ?>
              <li class="active"><span><?= $this->displayLanguageOption($langName)?></span></li>
            <?php endif; ?>
          <?php endforeach; ?>
        </ul>
      </li>
    <?php endif; ?>
    <li><a href="<?= $this->translate('URL::OPAC'); ?>" target="_blank"><?= $this->transEsc('Header_catalog')?></a></li>
    <li><a href="<?= $this->translate('URL::contact'); ?>" target="_blank"><?= $this->transEsc("Header_contact")?></a></li>
    <li><a href="<?= $this->translate('URL::search tips'); ?>" target="_blank"><?= $this->transEsc('Header_searchtipps')?></a></li>
    <li><a href="<?= $this->translate('URL::ILL'); ?>" target="_blank"><?= $this->transEsc('Header_interlibrary_loan')?></a></li>

    <li class="dropdown">
      <a href="#_" class="dropdown-toggle" data-toggle="dropdown"><?= $this->transEsc('more')?> <b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><a href="<?= $this->translate('URL::Databases'); ?>" target="_blank"><?= $this->transEsc('Databases')?></a></li>
        <li><a href="<?= $this->translate('URL::Journals'); ?>" target="_blank"><?= $this->transEsc('Journals')?></a></li>
        <li><a href="<?= $this->translate('URL::Norms'); ?>" target="_blank"><?= $this->transEsc('Header_norms')?></a></li>
        <li><a href="<?= $this->translate('URL::ThULB'); ?>" target="_blank"><?= $this->transEsc('Header_thulb')?></a></li>
        <li><a href="https://www.stadtbibliothek-jena.de/de/startseite/700073" target="_blank"><?= $this->transEsc('Header_eab_jena')?></a></li>
        <li><a href="<?= $this->translate('URL::Acquisition suggestion'); ?>" target="_blank"><?= $this->transEsc('Header_acquisition_suggestion')?></a></li>
      </ul>
    </li>
  </ul>
</div>
