<?php
  $errors = $this->errors ?? [];
  // Set up page title:
  $pageTitle = "Letter of Authorization";
  $this->headTitle($this->translate($pageTitle));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'
      . '<li>' . $this->transEsc($pageTitle) . '</li>';
?>

<?=$this->component('show-account-menu-button')?>

<div class="<?= $this->layoutClass('mainbody')?>">
  <h2><?= $this->transEsc($pageTitle); ?></h2>

  <div class="alert alert-info">
      <?= $this->transEsc('information_authorization'); ?>
  </div>

  <?= $this->flashmessages() ?>

  <form class="form-horizontal authority-form row g-3" method="post" name="authority">
    <p class="mb-0"><?= $this->transEsc('authorization_issued_for');?>:</p>

    <div class="col-lg-4">
      <label for="firstname" class="form-label fw-bold"><?= $this->transEsc('First Name'); ?></label>
      <input id="firstname" type="text" name="firstname" class="form-control<?= in_array('firstname', $errors) ? ' error' : ''; ?>" required placeholder="<?= $this->transEsc('First Name'); ?>" value="<?=$this->escapeHtmlAttr($this->request->getPost('firstname'))?>" />
    </div>
    <div class="col-lg-4">
      <label for="lastname" class="form-label fw-bold"><?= $this->transEsc('Last Name'); ?></label>
      <input id="lastname" type="text" name="lastname" class="form-control<?= in_array('lastname', $errors) ? ' error' : ''; ?>" required placeholder="<?= $this->transEsc('Last Name'); ?>" value="<?=$this->escapeHtmlAttr($this->request->getPost('lastname'))?>" />
    </div>
    <div class="col-lg-4">
      <label for="grantUntil" class="form-label fw-bold"><?= $this->transEsc('Valid Until'); ?></label>
      <input id="grantUntil" type="date" name="grantUntil" class="form-control<?= in_array('grantUntil', $errors) ? ' error' : ''; ?>" required placeholder="<?= $this->transEsc('Granted Until'); ?>" value="<?=$this->escapeHtmlAttr($this->request->getPost('grantUntil'))?>" min="<?= date("Y-m-d"); ?>">
    </div>

    <div class="align-items-baseline d-flex gap-2">
      <input id="check1" type="checkbox" name="check1" required />
      <label for="check1"><?= $this->transEsc('I_grant_authorization_to'); ?></label>
    </div>

    <div class="align-items-baseline d-flex gap-2 col-lg-">
      <input id="check2" type="checkbox" name="check2" required />
      <label for="check2"><?= $this->transEsc('as_authorization_issuer'); ?></label>
    </div>

    <div class="col-12 mb-2">
      <button class="btn btn-primary"><?= $this->transEsc('Create Letter of Authorization'); ?></button>
    </div>
  </form>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar" role="navigation" aria-label="<?=$this->transEsc('account_menu_label')?>">
  <?=$this->accountMenu()->render('letterofauthorization')?>
</div>
