<?php
  // Set up page title:
  $this->headTitle($this->translate('ill_delete_account'));

  // Disable breadcrumbs:
  $this->layout()->breadcrumbs = false;
?>

<?=$this->component('show-account-menu-button')?>

<div class="<?= $this->layoutClass('mainbody')?>">
  <h1 class="h2"><?= $this->transEsc('ill_delete_account')?></h1>
  <?= $this->flashmessages()?>

  <form action="<?=$this->url('ill-deleteaccountconfirmation')?>" method="post" data-lightbox data-lightbox-onclose="VuFind.refreshPage">
    <input type="hidden" name="csrf" value="<?= $this->auth()->getManager()->getCsrfHash(); ?>" />

    <p class="mt-2"><?= $this->transEsc('ill_delete_account_dsgvo'); ?></p>

    <label for="confirmation_email"><?= $this->transEsc('ill_delete_account_confirmation_email'); ?></label>
    <input type="email" id="confirmation_email" name="confirmation_email" class="form-control mt-2" value="<?=$this->userEmail?>">

    <input class="btn btn-primary mt-3" type="submit" name="delete" value="<?= $this->transEsc('ill_delete_account'); ?>" />
  </form>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar" role="navigation" aria-label="<?=$this->transEsc('account_menu_label')?>">
  <?=$this->accountMenu()->render('deleteaccount')?>
</div>
