<?php
  // Set up page title:
  $this->headTitle($this->translate('ill_delete_account'));

  // Disable breadcrumbs:
  $this->layout()->breadcrumbs = false;
?>

<?=$this->component('show-account-menu-button')?>

<div class="<?= $this->layoutClass('mainbody')?>">
  <h2><?= $this->transEsc('ill_delete_account')?></h2>
  <?= $this->flashmessages()?>

  <p class="mt-2"><?= $this->transEsc('ill_delete_account_dsgvo'); ?></p>
  <a href="/ILL/deleteaccountconfirmation" class="btn btn-primary" data-lightbox><?= $this->transEsc('ill_delete_account'); ?></a>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar" role="navigation" aria-label="<?=$this->transEsc('account_menu_label')?>">
  <?=$this->accountMenu()->render('deleteaccount')?>
</div>