<?php
  // Set up page title:
  $this->headTitle($this->translate('ill_forgot_password'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('ill_forgot_password') . '</li>';
?>

<?=$this->component('show-account-menu-button')?>

<div class="<?= $this->layoutClass('mainbody')?>">
  <h2><?= $this->transEsc('ill_forgot_password')?></h2>
  <?= $this->flashmessages()?>

  <div class="d-flex flex-wrap flex-md-nowrap gap-3">
    <div class="mt-0 mt-md-3 col-lg-6 flex-fill">
      <p><?= $this->translate('ill_forgot_password_info'); ?></p>
      <form href="/ILL/forgotpassword" method="post">
        <input type="hidden" name="csrf" value="<?= $this->auth()->getManager()->getCsrfHash(); ?>" />
        <input class="btn btn-primary" type="submit" name="forgot-password" value="<?= $this->transEsc('ill_forgot_password_reset'); ?>" />
      </form>
    </div>

    <div class="alert alert-warning col-6 flex-fill">
      <?= $this->translate('ill_forgot_password_warning'); ?>
    </div>
  </div>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar" role="navigation" aria-label="<?=$this->transEsc('account_menu_label')?>">
  <?=$this->accountMenu()->render('forgotillpassword')?>
</div>