<?php
  // Set up convenience variables:
  $account = $this->auth()->getManager();
  $user = $account->isLoggedIn();
  $openUrl = $this->openUrl($this->tab->getRecordDriver(), 'holdings');
  $openUrlActive = $openUrl->isActive();

  // Account for replace_other_urls setting
  $offlineMode = $this->ils()->getOfflineMode();

  try {
    $holdings = $this->driver->getHoldings();
  }
  catch (\VuFind\Exception\ILS $e) {
    $holdings = ['holdings' => []];
    $offlineMode = 'ils-offline';
  }

  $onlineContentLinks = $this->thulb_onlineContent($this->driver);
?>

<?= $this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>

<?php if (!empty($holdings['blocks'])):?>
  <div id="account-block-msg" class="alert alert-danger">
      <?= $this->transEsc('account_block_options_missing', ['%%details%%' => implode('; ', $holdings['blocks'])]) ?>
  </div>
<?php endif; ?>

<?php // ILS offline ?>
<?= ($offlineMode == "ils-offline" && empty($holdings)) ? $this->render('Helpers/ils-offline.phtml', ['offlineModeMsg' => 'ils_offline_holdings_message']) : ''?>

<?php // unused ??? ?>
<?php if (($this->ils()->getHoldsMode() == 'driver' && !empty($holdings['holdings'])) || $this->ils()->getTitleHoldsMode() == 'driver'): ?>
  <?php if ($account->loginEnabled() && $offlineMode != 'ils-offline'): ?>
    <?php if (!$user): ?>
      <div class="alert alert-info">
        <a href="<?= $this->recordLinker()->getTabUrl($this->driver, 'Holdings')?>?login=true&amp;catalogLogin=true" data-lightbox><?= $this->transEsc("Login")?></a> <?= $this->transEsc("hold_login")?>
      </div>
    <?php elseif (!$user->cat_username): ?>
      <div class="alert alert-info">
        <?= $this->translate("hold_profile_html", ['%%url%%' => $this->recordLinker()->getTabUrl($this->driver, 'Holdings') . '?catalogLogin=true'])?>
      </div>
    <?php endif; ?>
  <?php endif; ?>
<?php endif; ?>

<?php // unused ??? ?>
<?php $holdingTitleHold = $this->driver->tryMethod('getRealTimeTitleHold'); if (!empty($holdingTitleHold)): ?>
  <a class="placehold" data-lightbox title="<?= $this->transEscAttr('request_place_text')?>" href="<?= $this->recordLinker()->getRequestUrl($holdingTitleHold)?>">
    <i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?= $this->transEsc('title_hold_place')?>
  </a>
<?php endif; ?>

<?php // online holdings ?>
<?php if(!empty($onlineContentLinks)): ?>
  <div class="online-access striped" summary="<?= $this->transEscAttr('Holdings details from')?> <?= $this->transEscAttr('Remote')?>">
    <?php foreach($onlineContentLinks as $contentLink): ?>
    <div class="row">
      <?php if(empty($contentLink)) continue; ?>
      <?php $linkData = $contentLink['data'] ?? []; ?>
      <div class="flex flex-dir-col pb-1 pl-1 pr-2">
        <div class="online-content-wrapper mr-2 mb-2">
          <?= $this->record($this->driver)->renderTemplate('onlineContent.phtml', ['linkData' => $contentLink]); ?>
          <?= $this->render('record/broken-link.phtml'); ?>
        </div>
        <div class="col-text">
          <?php if($linkData['remotetitle'] ?? false):?>
            [<?php echo $linkData['remotetitle']; ?>]
          <?php endif; ?>

          <?php /* BESTANDSANGABEN */ ?>
          <?= $this->render('RecordTab/access/holding-chronology.phtml', ['holding' => $linkData]); ?>

          <?php /* ANMERKGUNGEN */ ?>
          <?= $this->render('RecordTab/access/holding-comments.phtml', ['holding' => $linkData]); ?>

          <?php if(isset($linkData['remotedesc']) && $linkData['remotedesc'] === $this->transEsc('get_citation')): ?>
            <div class="item-notes">
              <?= $this->transEsc('explain_reference') ?>
            </div>
          <?php endif; ?>

          <?php if (in_array($contentLink['type'] ?? '', ['fulltext', 'reference'])) : ?>
            <?= $this->render('RecordTab/access/citations.phtml'); ?>
          <?php endif; ?>
        </div>
      </div>
    </div>
    <?php endforeach; ?>
  </div>
<?php endif; ?>

<?php // physical holdings ?>
<?php if (!empty($holdings)): ?>
  <?php foreach ($holdings['holdings'] as $holdingKey => $holding): ?>
    <?php if($holdingKey == 'Remote') continue; ?>
    <?= $this->render('RecordTab/access/physicalHoldingLocation.phtml', ['holding' => $holding, 'driver' => $this->driver]); ?>
  <?php endforeach; ?>
<?php endif; ?>

<?php // unused ??? ?>
<?php $history = $this->driver->getRealTimeHistory(); ?>
<?php if (is_array($history) && !empty($history)): ?>
  <h3><?= $this->transEsc("Most Recent Received Issues")?></h3>
  <table class="table table-striped">
    <?php foreach ($history as $row): ?>
      <tr><td><?= $this->escapeHtml($row['issue'])?></td></tr>
    <?php endforeach; ?>
  </table>
<?php endif; ?>

<?php if(empty($onlineContentLinks) && !$holdings['total']): ?>
  <?= $this->render('RecordTab/access/recommendSeries.phtml', ['driver' => $this->driver]); ?>
<?php endif; ?>

<?php if(is_callable([$this->driver, 'isFormat']) && $this->driver->isFormat('Journal')
    && $this->record($this->driver)->hasNonArticleTab($this)): ?>
    <?= $this->transEsc('see volumes tab for listing and ordering of volumes'); ?>
<?php endif; ?>
