<?php foreach ($checkboxFilters as $current): ?>
  <?php
    $isHidden = !($results->getResultTotal() > 0 || $current['selected'] || $current['alwaysVisible']);
    $href = $current['selected']
      ? $results->getUrlQuery()->removeFilter($current['filter'])
      : $results->getUrlQuery()->addFilter($current['filter']);
  ?>
  <div class="facet<?=$current['selected'] ? ' active' : ''?>" data-facet="<?=$this->escapeHtmlAttr($current['filter'])?>">
    <a class="checkbox-filter icon-link<?=$isHidden ? ' hidden' : '' ?>" href="<?=$href ?>">
      <?php if ($current['selected']): ?>
        <span class="sr-only"><?=$this->transEsc('clear_tag_filter') ?></span>
      <?php endif; ?>

      <?= $this->icon($current['selected'] ? 'facet-checked' : 'facet-unchecked', [
          'class' => 'icon-link__icon',
          'data-checked' => $current['selected'] ? 'true' : 'false',
      ]) ?>
      <span class="icon-link__label">
        <?=$this->transEsc($current['desc']) ?>

        <?php if($current['desc'] == 'include_references'): ?>
          <i class="fa fa-info-circle" onclick="event.preventDefault(); event.stopPropagation(); VuFind.lightbox.alert('<?= $this->transEsc('reference_facet_info', ["'" => "\\'"]); ?>', 'info');"></i>
        <?php endif; ?>
      </span>

      <?php if (!$current['selected']): ?>
        <span class="badge avail-count"></span>
      <?php endif; ?>
    </a>
  </div>
<?php endforeach; ?>
