<?php $sdUrl = $this->thulb_serviceDesk('broken-link', [
    'url' => $this->serverUrl($this->recordLinker()->getUrl($this->driver)),
    'titleData' => $this->driver->getTitle(),
    'summary' => $this->transEsc('Access problem via ThULB-Suche')
]); ?>
<a href="<?= $sdUrl; ?>" class="broken-link" title="<?= $this->transEsc('Broken link?'); ?>" target="_blank">
  <span class="broken-link-description"><?= $this->transEsc('Access problem?'); ?></span>
  <i class="broken-link-icon"></i>
</a>
