<?php
  try {
    $holdings = $this->driver->getHoldingsToOrderOrReserve();
  }
  catch (\VuFind\Exception\ILS $e) {
    $holdings = ['holdings' => []];
  }
?>

<h2><?= $this->driver->getTitle(); ?></h2>

<table class="table table-striped table-order-reserve">
  <tr>
    <th class="col-sm-4"><?= $this->transEsc('Location'); ?></th>
    <th class="col-sm-2"><?= $this->transEsc('Call Number'); ?></th>
    <th class="col-sm-2"><?= $this->transEsc('Due'); ?></th>
    <th class="col-sm-2">&nbsp;</th>
  </tr>
  <?php foreach($holdings as $location => $items): ?>
    <?php foreach($items as $item): ?>
      <tr>
        <td class="col-sm-4"><?= $item['location']; ?></td>
        <td class="col-sm-2"><?= $item['callnumber']; ?></td>
        <td class="col-sm-2">
          <?= $item['duedate']; ?>
          <?php if($item['requests_placed'] ?? false): ?>
            <br>(<?= $item['requests_placed'] . 'x ' . $this->transEsc('ils_hold_item_requested'); ?>)
          <?php endif; ?>
        </td>
        <td class="col-sm-2">
          <?php if($item['availability']->isAvailable() ?? false): ?>
            <?php foreach($this->thulb_holdingHelper()->getRequestLinks($item, $this->driver->isNewsPaper()) as $linkData): ?>
              <a class="<?= $linkData['classes']; ?>" data-lightbox href="<?= $linkData['link']; ?>"><?= $linkData['icon'] ?? ''; ?><?= $this->transEsc($linkData['desc']); ?></a>
            <?php endforeach; ?>
          <?php else: ?>
            <?php if($linkData = $this->thulb_holdingHelper()->getRecallLink($item)): ?>
              <a class="<?= $linkData['classes']; ?>" data-lightbox href="<?= $linkData['link']; ?>"><?= $linkData['icon'] ?? ''; ?><?= $this->transEsc($linkData['desc']); ?></a>
            <?php endif; ?>
          <?php endif; ?>
        </td>
      </tr>
    <?php endforeach; ?>
  <?php endforeach; ?>
</table>
