<?= $this->transEsc('Hello'); ?> <?= $this->name; ?>,

<?= $this->transEsc('Email::letter_of_authorisation_email_paragraph_1'); ?>


<?= $this->transEsc('Email::letter_of_authorisation_email_paragraph_2'); ?>


<?= $this->transEsc('Email::letter_of_authorisation_email_paragraph_3'); ?>


<?= $this->transEsc('Email::letter_of_authorisation_email_paragraph_4'); ?>


<?= $this->transEsc('Email::letter_of_authorisation_email_paragraph_5'); ?>


<?= $this->transEsc('Email::Yours sincerely'); ?>

ThULB Jena
