<?php
  // AJAX Check record?
  $check = $item['check'] ?? false;
  $checkStorageRetrievalRequest = $item['checkStorageRetrievalRequest'] ?? false;
  $checkILLRequest = $item['checkILLRequest'] ?? false;

  $holdingHelper = $this->thulb_holdingHelper();
?>

<?php if ($item['reserve'] == "Y"): ?>
  <link property=\"availability" href="http://schema.org/InStoreOnly" />
  <?= $this->transEsc("On Reserve - Ask at Circulation Desk"); ?><br />
<?php endif; ?>

<?php /* Embed item structured data: library, barcode, call number */ ?>
<?php if ($item['location']): ?>
  <meta property="seller" content="<?= $this->escapeHtmlAttr($item['location']); ?>" />
<?php endif; ?>
<?php if ($item['barcode']): ?>
  <meta property="serialNumber" content="<?= $this->escapeHtmlAttr($item['barcode']); ?>" />
<?php endif; ?>
<?php if ($item['callnumber']): ?>
  <meta property="sku" content="<?= $this->escapeHtmlAttr($item['callnumber']); ?>" />
<?php endif; ?>

<?php /* Declare that the item is to be borrowed, not for sale */ ?>
<link property="businessFunction" href="http://purl.org/goodrelations/v1#LeaseOut" />
<link property="itemOffered" href="#record" />

<?php if ($item['availability']->is(\VuFind\ILS\Logic\AvailabilityStatusInterface::STATUS_UNKNOWN) ?? false): ?>
  <span class="<?= $this->availabilityStatus()->getClass($item['availability']); ?>"><?= $this->transEsc($item['availability']->getStatusDescription()); ?><link property="availability" href="<?= $item['availability']->getSchemaAvailabilityUri(); ?>" /></span>
<?php elseif($item['availability']->isAvailable()): ?>
  <?php /* Begin AVAILABLE Items (Holds) */ ?>
  <span class="<?= $this->availabilityStatus()->getClass($item['availability']); ?>"><?= $this->transEsc($item['availability']->getStatusDescription()); ?><link property="availability" href="<?= $item['availability']->getSchemaAvailabilityUri(); ?>" /></span>

  <?php foreach($holdingHelper->getRequestLinks($item, $this->driver->isNewsPaper()) as $linkData): ?>
    <a class="<?= $linkData['classes']; ?>" data-lightbox href="<?= $linkData['link']; ?>"><?= $linkData['icon'] ?? ''; ?><?= $this->transEsc($linkData['desc']); ?></a>
  <?php endforeach; ?>

  <?php /* Nicht leihbar? Also Lesesaal! */ ?>
  <?php if ($readingRoom = $holdingHelper->getReadingRoomOnlyString($item)): ?>
    <br><?= $readingRoom; ?>
  <?php endif; ?>
<?php else: ?>
  <?php /* Begin UNAVAILABLE Items (Recalls) */ ?>
  <?php if (($item['returnDate'] ?? false) || ($item['duedate'] ?? false) || (isset($item['holdtype']) && $item['holdtype'] === 'recall')): ?>
    <?php /* is there a duedate? > "ausgeliehen" */ ?>
    <span class="<?= $this->availabilityStatus()->getClass($item['availability']); ?>"><?= $this->transEsc($item['availability']->getStatusDescription()); ?><link property="availability" href="<?= $item['availability']->getSchemaAvailabilityUri(); ?>" /></span>
  <?php else: ?>
    <?php /* no duedate? > "nicht verfügbar" */ ?>
    <span class="text-danger"><?= $this->transEsc('Unavailable'); ?><link property="availability" href="http://schema.org/OutOfStock" /></span>
  <?php endif; ?>

  <?php if ($item['returnDate'] ?? false): ?>
    &ndash; <?= $this->escapeHtml($item['returnDate']); ?>
  <?php endif; ?>

  <?php if ($item['duedate'] ?? false): ?>
    &ndash; <?= $this->transEsc("Due"); ?>: <?= $this->escapeHtml($item['duedate']); ?>
  <?php endif; ?>

  <?php if ($item['link'] ?? false): ?>
    <?php $recallLink = $holdingHelper->getRecallLink($item); ?>
    <a class="<?= $recallLink['classes']; ?>" data-lightbox href="<?= $recallLink['link']; ?>"><?= $recallLink['icon'] ?? ''; ?><?= $this->transEsc($recallLink['desc']); ?></a>
  <?php endif; ?>

  <?= $holdingHelper->getRequestsPlacedString($item); ?>
<?php endif; ?>