<?=$this->transEsc('Email::username_%%', ['%%username%%' => $this->username])?>


<?=$this->transEsc('Email::salutation', ['%%firstname%%' => $this->firstname, '%%lastname%%' => $this->lastname])?>


<?=$this->transEsc('Email::Thank you for the request_article')?>


<?php if($this->departmentId == 'Mag'): ?>
<?=$this->transEsc('Email::provisioning_via_account')?>


<?=$this->transEsc('Email::please note')?>: <?=$this->transEsc('Email::not loanable')?>

<?php endif; ?>

<?=$this->transEsc('Email::Request details')?>:

<?=$this->transEsc('Email::Article title')?>: <?=$this->title?>

<?=$this->transEsc('Email::Series')?>: <?=$this->series?>

<?=$this->transEsc('Email::comment', ['%%comment%%' => $this->comment])?>


<?php if($this->departmentId == 'Mag'): ?>
<?=$this->transEsc('Email::not listed')?>:

    • <?=$this->transEsc('Email::not listed, phone')?>

    • <?=$this->transEsc('Email::not listed, mail', ['%%email%%' => $this->informationEmail])?>
<?php else: ?>
<?=$this->transEsc('Email::provisioning_via_' . ($this->departmentId == 'Mag5' ? 'account' : 'email'))?>


<?=$this->transEsc('Email::questions at', ['%%email%%' => $this->informationEmail])?>
<?php endif; ?>


<?=$this->transEsc('Email::complimentary close')?>

<?=$this->transEsc('Email::thulb_signature')?>
