<?php
  // Set up page title:
  $this->headTitle($this->translate('Holds and Recalls'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Holds and Recalls') . '</li>';
?>

<div class="<?= $this->layoutClass('mainbody')?>">
  <?= $this->flashmessages()?>

  <?= $this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>

  <h2><?= $this->transEsc('Reserved items'); ?></h2>
  <?php if (!empty($this->reservedList)): ?>
    <?php if ($this->cancelForm): ?>
    <form name="cancelForm" class="inline" method="post" id="cancelHold">
    <input type="hidden" id="submitType" name="cancelSelected" value="1"/>
    <input type="hidden" id="cancelConfirm" name="confirm" value="0"/>
    <div class="btn-group">
      <input id="cancelSelected" name="cancelSelected" type="submit" value="<?= $this->transEscAttr("hold_cancel_selected") ?>" class="btn btn-default dropdown-toggle" data-toggle="dropdown"/>
      <ul class="dropdown-menu">
        <li class="disabled"><a><?= $this->transEsc("confirm_hold_cancel_selected_text") ?></a></li>
        <li><a href="#" onClick="$('#cancelConfirm').val(1);$('#submitType').attr('name','cancelSelected');$(this).parents('form').submit(); return false;"><?= $this->transEsc('confirm_dialog_yes') ?></a></li>
        <li><a href="#" onClick="return false;"><?= $this->transEsc('confirm_dialog_no')?></a></li>
      </ul>
    </div>
    <div class="btn-group">
      <input id="cancelAll" name="cancelAll" type="submit" value="<?= $this->transEscAttr("hold_cancel_all") ?>" class="btn btn-default dropdown-toggle" data-toggle="dropdown"/>
      <ul class="dropdown-menu">
        <li class="disabled"><a><?= $this->transEsc("confirm_hold_cancel_all_text") ?></a></li>
        <li><a href="#" onClick="$('#cancelConfirm').val(1);$('#submitType').attr('name','cancelAll');$(this).parents('form').submit(); return false;"><?= $this->transEsc('confirm_dialog_yes') ?></a></li>
        <li><a href="#" onClick="return false;"><?= $this->transEsc('confirm_dialog_no')?></a></li>
      </ul>
    </div>
    <?php endif; ?>

    <?php foreach ($this->reservedList as $resource): ?>
      <?= $this->render('holds/holdsandsrr/item.phtml', [
        'cancelForm' => $this->cancelForm,
        'cancelResults' => $this->cancelResults,
        'disableCheckboxes' => $this->disableCheckboxes,
        'pickup' => $this->pickup,
        'resource' => $resource,
      ]); ?>
      <hr/>
    <?php endforeach; ?>
    <?php if ($this->cancelForm): ?></form><?php endif; ?>
  <?php else: ?>
    <?= $this->transEsc('You do not have any recalls placed') ?>
    <hr/>
  <?php endif; ?>

  <h2><?= $this->transEsc('Ordered items'); ?></h2>
  <?php if (!empty($this->orderedList)): ?>
    <?php foreach ($this->orderedList as $resource): ?>
      <?= $this->render('holds/holdsandsrr/item.phtml', [
        'cancelForm' => false,
        'cancelResults' => false,
        'disableCheckboxes' => true,
        'pickup' => $this->pickup,
        'resource' => $resource,
      ]); ?>
      <hr/>
    <?php endforeach; ?>
  <?php else: ?>
    <?= $this->transEsc('You do not have any holds placed') ?>
  <?php endif; ?>
</div>

<div class="<?= $this->layoutClass('sidebar')?>">
  <?= $this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'holdsandsrr'])?>
</div>
