<?php foreach ($checkboxFilters as $current): ?>
  <div class="facet">
    <?php $urlAddFilter = $results->getUrlQuery()->addFilter($current['filter']); ?>
    <?php $urlRemoveFilter = $results->getUrlQuery()->removeFilter($current['filter']); ?>
    <a class="checkbox-filter<?php if (!($results->getResultTotal() > 0 || $current['selected'] || $current['alwaysVisible'])): ?> hidden<?php endif; ?>"
       href="<?= $current['selected'] ? $urlRemoveFilter : $urlAddFilter; ?>"
       data-facet="<?= $this->escapeHtmlAttr($current['filter']) ?>"
       data-facet="<?= $this->escapeHtmlAttr($current['filter']) ?>">
      <?php if ($current['selected']): ?>
        <span class="sr-only"><?= $this->transEsc('clear_tag_filter') ?></span>
      <?php endif; ?>
      <span class="text">
        <i class="fa fa-<?= $current['selected'] ? 'check-square-o' : 'square-o' ?>"></i>
        <?= $this->transEsc($current['desc']) ?>

        <?php if($current['desc'] == 'include_references'): ?>
          <i class="fa fa-info-circle" onclick="event.preventDefault(); event.stopPropagation(); VuFind.lightbox.showAlert('<?= $this->transEsc('reference_facet_info'); ?>', 'info');"></i>
        <?php endif; ?>
      </span>
      <?php if (!$current['selected']): ?>
        <span class="badge avail-count"></span>
      <?php endif; ?>
    </a>
  </div>
<?php endforeach; ?>
