<?php
  $toggleUrl = $this->facet['isApplied']
    ? $this->urlBase . $this->url->removeFacet($this->group, $this->facet['value'], $this->facet['operator'])
    : $this->urlBase . $this->url->addFacet($this->group, $this->facet['value'], $this->facet['operator']);

  $hasSubLinks = $this->exclude && !$this->facet['isApplied'];

  $classList = ['facet', 'js-facet-item'];
  if ($this->facet['isApplied']) {
    $classList[] = 'active';
  }
  if ($this->facet['operator'] == 'OR') {
    $classList[] = 'facetOR';
  }
  if ($this->facet['operator'] == 'AND') {
    $classList[] = 'facetAND';
  }

  $displayText = '-';
  if (!empty($this->facet['displayText'])) {
    $displayText = $this->escapeHtml($this->facet['displayText']);
  } elseif (!empty($this->facet['value'])) {
    $displayText = $this->escapeHtml($this->facet['value']);
  }
  $displayText = '<span class="facet-value ml-1">' . $displayText . '</span>';

  if (!$this->facet['isApplied'] && $this->facet['operator'] == 'OR') {
    $displayText = $this->icon('facet-unchecked') . $displayText;
  }
?>
<?php if ($hasSubLinks): ?>
  <div class="<?=implode(' ', $classList) ?>">
<?php else: ?>
  <a href="<?=$toggleUrl ?>" class="<?=implode(' ', $classList) ?>" data-title="<?=$this->escapeHtmlAttr($this->facet['displayText']) ?>" data-count="<?=$this->facet['count'] ?>"<?php if($this->facet['isApplied']): ?> title="<?=$this->transEscAttr('applied_filter') ?>"<?php endif;?> data-lightbox-ignore>
<?php endif; ?>

  <?php if ($this->facet['isApplied']): ?>
    <span class="status"><i class="fa fa-check" aria-hidden="true"></i></span>
  <?php endif; ?>

  <?php if ($hasSubLinks): ?>
    <a class="text" href="<?=$toggleUrl ?>" data-lightbox-ignore data-title="<?=$this->escapeHtmlAttr($this->facet['displayText']) ?>" data-count="<?=$this->facet['count'] ?>"<?php if($this->facet['isApplied']): ?> title="<?=$this->transEscAttr('applied_filter') ?>"<?php endif;?>>
      <?=$displayText ?>
    </a>
  <?php else: ?>
    <span class="text">
      <?=$displayText ?>
    </span>
  <?php endif; ?>

  <?php if (!$this->facet['isApplied'] && null !== $this->facet['count']): ?>
    <span class="badge">
      <?php $currentCount = $this->localizedNumber($this->facet['count']); ?>
      <span class="sr-only"><?=$this->transEsc('result_count', ['%%count%%' => $currentCount]) ?></span>
      <span aria-hidden="true"><?=$currentCount ?></span>
    </span>
  <?php endif; ?>

  <?php if ($this->exclude && !$this->facet['isApplied']): ?>
    <?php $excludeURL = $this->urlBase . $this->url->addFacet($this->group, $this->facet['value'], 'NOT'); ?>
    <a href="<?=$excludeURL ?>" data-lightbox-ignore class="exclude">
      <?=$this->icon('facet-exclude') ?>
      <span class="sr-only"><?=$this->transEsc('exclude_facet') ?></span>
    </a>
  <?php endif; ?>

<?=$hasSubLinks ? '</div>' : '</a>'; ?>
