<?=$this->layout()->content?>

<?php $layoutContext = $this->layoutContext ?? 'lightbox'; ?>
<?php if($layoutContext != 'tabs'): ?>
  <?=$this->piwik(['lightbox' => true])?>
  <?=$this->matomo(['context' => $layoutContext])?>
  <?=$this->googleanalytics($this->serverUrl(true))?>
<?php endif; ?>

<?php if ($this->session()->put('reset_account_status', null) && $this->auth()->getManager()->ajaxEnabled()) {
  $this->inlineScript()->setAllowArbitraryAttributes(true);
  echo $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, 'VuFind.account.clearAllCaches();', 'SET', ['data-lightbox-run' => 'always']);
}
