<?php if(!empty($locationData)): ?>
  <?php $weekday = date('N'); ?>
  <div id="location-data-<?= $locationData['id']; ?>" class="location-data-wrapper">
    <div class="location-data">
      <h4><?= $locationData['name']; ?></h4>

      <h5><?= $this->transEsc('Address'); ?>: <a href="<?= $locationData['googleMapsUrl']; ?>" target="_blank" data-lightbox-ignore><i class="fa fa-map-marker"></i></a></h5>
      <div class="ws-nowrap">
        <?php foreach (explode('/', $locationData['address']) as $addressPart): ?>
          <?= $addressPart; ?><br>
        <?php endforeach; ?>
      </div>

      <h5><?= $this->transEsc('Phone Number'); ?>:</h5>
      <div><?= $locationData['phone']; ?></div>

      <h5><?= $this->transEsc('Opening hours'); ?>:</h5>
      <table class="mb-2">
        <?php foreach($locationData['openingHours'] as $jdday => $day): ?>
          <?php
            $class = '';
            if (($weekday % 7) == $jdday) {
              $class = ($locationData['openCloseToday']['nowOpen'] ?? false) ? 'fw-bold text-success' : 'fw-bold text-danger';
            }
          ?>
          <tr>
            <td class="pr-2 <?= $class; ?>"><?= $this->transEsc($day['day']); ?>:</td>
            <td class="<?= $class; ?>" ><?= $this->transEsc($day['formattedTime']); ?></td>
          </tr>
        <?php endforeach; ?>
      </table>

      <a href="<?= $this->holding['locationhref']; ?>" target="_blank" data-lightbox-ignore><?= $this->transEsc('Further location information'); ?></a>
    </div>
  </div>
<?php endif; ?>
