<?php
  $currentPath = '';
  if($this->results == null || ($this->ajaxTab ?? false)) {
      $currentPath = $this->currentPath() . '?';
  }

  $liAttrs = $this->htmlAttributes([
    'class' => array_merge(['page-item'], $this->liClasses ?? []),
  ]);
  $aAttrs = $this->htmlAttributes([
    'class' => 'page-link',
    'aria-label' => $this->label,
    'href' => null !== $this->results
      ? $currentPath . $this->results->getUrlQuery()->setPage($this->page)->getParams(false)
      : $currentPath . http_build_query(array_merge($this->params ?? [], ['page' => $this->page])),
  ]);
  if ($this->page === $this->current) {
    $liAttrs->add('class', 'active');
    $liAttrs['aria-current'] = 'page';
  }
?>
<li<?=$liAttrs?>>
  <a<?=$aAttrs?>>
    <?=$contentHtml?>
  </a>
</li>
