<nav class="hidden-xs">
  <div class="container">
    <ul class="nav navbar-nav">
      <li><a href="https://www.thulb.uni-jena.de/impressum.html" target="_blank"><?= $this->transEsc('Footer_imprint')?></a></li>
      <li><a href="<?= $this->config()->get('config.staging')->Site->url . $_SERVER['REQUEST_URI']; ?>" target="_blank">Im Testsystem öffnen</a></li>
      <li><a href="<?= $this->config()->get('config.production')->Site->url . $_SERVER['REQUEST_URI']; ?>" target="_blank">Im Livesystem öffnen</a></li>
    </ul>
  </div>
</nav>
