<ul class="nav navbar-nav navbar-left">
  <?php if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
    <?=$this->component('menu-button', [
      'toggleLabel' => $this->transEsc('Language') . ' ',
      'wrapperClass' => 'language visible-xs visible-sm dropdown-colored-sm',
      'wrapperTag' => 'li',
      'toggleClass' => 'ps-3',
      'href' => '#_',
      'menuItems' => array_map(
        function ($langCode, $langName) {
          return [
            'label' => $this->displayLanguageOption($langName),
            'url' => $this->url()->addQueryParameters(['lng' => $langCode]),
            'selected' => $this->layout()->userLang == $langCode,
          ];
        },
        array_keys($this->layout()->allLangs),
        array_values($this->layout()->allLangs),
      ),
    ]) ?>
  <?php endif; ?>

  <li><a class="ps-3" href="https://www.thulb.uni-jena.de/fileadmin/ims_ablageordner/pdf/Bibsuche_Suchtipps.pdf" target="_blank"><?= $this->transEsc("Search Tips")?></a></li>
  <li><a class="ps-3" href="<?= $this->translate('URL::Header_contact'); ?>" target="_blank"><?= $this->transEsc("Header_contact")?></a></li>

  <li class="dropdown dropdown-colored-sm">
    <a href="#_" class="ps-3 dropdown-toggle arrow-down" data-toggle="dropdown"><?= $this->transEsc('Found nothing')?></a>
    <ul class="dropdown-menu">
      <li class="dropdown__item"><a class="ps-3 dropdown__link dropdown-item" href="<?= $this->translate('URL::OPAC Eisenach'); ?>" target="_blank"><?= $this->transEsc('Katalog Eisenach')?></a></li>
      <li class="dropdown__item"><a class="ps-3 dropdown__link dropdown-item" href="<?= $this->translate('URL::OPAC Gera'); ?>" target="_blank"><?= $this->transEsc('Katalog Gera')?></a></li>
      <li class="dropdown__item"><a class="ps-3 dropdown__link dropdown-item" href="<?= $this->translate('URL::GVK'); ?>" target="_blank"><?= $this->transEsc('Header_interlibrary_loan')?></a></li>
    </ul>
  </li>
</ul>
