<?php $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
<div id="record<?= $this->escapeHtmlAttr($resource->getUniqueId()) ?>" class="row result">
  <?php if ($this->cancelForm && isset($ilsDetails['cancel_details']) && !$this->disableCheckboxes): ?>
    <?php $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $resource->getUniqueId()); ?>
    <input type="hidden" name="cancelAllIDS[]" value="<?= $this->escapeHtmlAttr($ilsDetails['cancel_details']) ?>" />
    <div class="col-xs-1">
      <input type="checkbox" name="cancelSelectedIDS[]" value="<?= $this->escapeHtmlAttr($ilsDetails['cancel_details']) ?>" id="checkbox_<?= $safeId?>" />
    </div>
  <?php endif; ?>

  <div class="col-sm-9 col-xs-11">
  <?php
    // If this is a non-missing Solr record, we should display a link:
    if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
      $title = $this->record($resource)->getTitleHtml();
      echo '<a href="' . $this->recordLinker()->getUrl($resource)
        . '" class="title truncate">' . $title . '</a>';
    } else if (isset($ilsDetails['title']) && !empty($ilsDetails['title'])){
      // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
      echo $this->escapeHtml($ilsDetails['title']);
      echo '<br />';
    } else {
      // Last resort -- indicate that no title could be found.
      echo $this->transEsc('Title not available');
      echo '<br />';
    }
    ?>
    <?php $listAuthors = $resource->getPrimaryAuthors(); if (!empty($listAuthors)): ?>
      <?= $this->transEsc('by')?>:
      <a href="<?= $this->record($resource)->getLink('author', $listAuthors[0])?>"><?= $this->escapeHtml($listAuthors[0])?></a><?php if (count($listAuthors) > 1): ?>, <?= $this->transEsc('more_authors_abbrev')?><?php endif; ?><br/>
    <?php endif; ?>
    <?php if (isset($ilsDetails['volume']) && !empty($ilsDetails['volume'])): ?>
      <strong><?= $this->transEsc('Volume')?>:</strong> <?= $this->escapeHtml($ilsDetails['volume'])?>
      <br />
    <?php endif; ?>

    <?php if (isset($ilsDetails['callnumber'])) : ?>
      <strong><?= $this->transEsc('sort_callnumber')?>:</strong> <?= $this->escapeHtml($ilsDetails['callnumber'])?>
      <br />
    <?php endif; ?>

    <?php if (!empty($ilsDetails['requestGroup'])): ?>
      <strong><?= $this->transEsc('hold_requested_group') ?>:</strong> <?= $this->transEsc('request_group_' . $ilsDetails['requestGroup'], null, $ilsDetails['requestGroup'])?>
      <br />
    <?php endif; ?>

    <?php /* Depending on the ILS driver, the "location" value may be a string or an ID; figure out the best
         value to display... */ ?>
    <?php $pickupDisplay = ''; ?>
    <?php $pickupTranslate = false; ?>
    <?php if (isset($ilsDetails['location'])): ?>
      <?php if ($this->pickup): ?>
        <?php foreach ($this->pickup as $library): ?>
          <?php if ($library['locationID'] == $ilsDetails['location']): ?>
            <?php $pickupDisplay = $library['locationDisplay']; ?>
            <?php $pickupTranslate = true; ?>
          <?php endif; ?>
        <?php endforeach; ?>
      <?php endif; ?>
      <?php if (empty($pickupDisplay)): ?>
        <?php $pickupDisplay = $ilsDetails['location']; ?>
      <?php endif; ?>
    <?php endif; ?>

    <?php if (!empty($ilsDetails['create'])): ?>
      <strong><?= $this->transEsc('Created') ?>:</strong> <?= $this->escapeHtml($ilsDetails['create']) ?>
      <br />
      <?php if (!empty($ilsDetails['expire'])): ?>|<?php endif; ?>
    <?php endif; ?>

    <?php if (isset($this->cancelResults['items'])): ?>
      <?php foreach ($this->cancelResults['items'] as $itemId => $cancelResult): ?>
        <?php if ($itemId == $ilsDetails['item_id'] && $cancelResult['success'] == false): ?>
          <div class="alert alert-danger"><?= $this->transEsc($cancelResult['status']) ?><?php if ($cancelResult['sysMessage']) echo ' : ' . $this->transEsc($cancelResult['sysMessage']); ?></div>
        <?php endif; ?>
      <?php endforeach; ?>
    <?php endif; ?>

    <?php if (isset($ilsDetails['available']) && $ilsDetails['available'] == true): ?>
      <p><span class="label label-success"><?= $this->transEsc("hold_available") ?></span></p>
    <?php elseif (isset($ilsDetails['in_transit']) && $ilsDetails['in_transit']): ?>
      <p><span class="label label-success"><?= $this->transEsc('request_in_transit') . (is_string($ilsDetails['in_transit']) ? ': ' . $this->transEsc('institution_' . $ilsDetails['in_transit'], [], $ilsDetails['in_transit']) : '') ?></span></p>
    <?php endif; ?>

    <?php if (isset($ilsDetails['type']) && $ilsDetails['type'] === 'rejected') : ?>
      <?php $transParams = ['%%location%%' => isset($ilsDetails['location']) ? $ilsDetails['location'] : ' Zentrale Ausleihe'];?>
      <span class="text-danger"><?= $this->transEsc('Consultation necessary', $transParams)?></span>
      <br />
    <?php endif; ?>

    <?php if (isset($ilsDetails['cancel_link'])): ?>
      <p><a href="<?= $this->escapeHtmlAttr($ilsDetails['cancel_link']) ?>"><?= $this->transEsc("hold_cancel") ?></a></p>
    <?php endif; ?>
  </div>
</div>