<?php
  // Set up some convenience variables:
  $id = $this->driver->getUniqueId();
  $source = $this->driver->getSourceIdentifier();
  if (isset($this->list) && is_object($this->list)) {
    $list_id = $this->list->getId();
    $user_id = $this->list->getUser()->getId();
  } else {
    $list_id = null;
    $user_id = $this->user ? $this->user->id : null;
  }
  $editable = $this->user && $user_id === $this->user->id;

  $recordLinker = $this->recordLinker($this->results);
  $coverDetails = $this->record($this->driver)->getCoverDetails('list-entry', 'medium', $recordLinker->getUrl($this->driver));
  $cover = $coverDetails['html'];
  $thumbnail = false;
  $thumbnailAlignment = $this->record($this->driver)->getThumbnailAlignment('list');
  if ($cover):
    ob_start(); ?>
    <div class="hidden-xs media-<?= $thumbnailAlignment ?> <?= $this->escapeHtmlAttr($coverDetails['size'])?>">
      <?= $cover ?>
    </div>
    <?php $thumbnail = ob_get_contents(); ?>
  <?php ob_end_clean(); ?>
<?php endif; ?>

<div class="result<?php if($this->driver->supportsAjaxStatus()): ?> ajaxItem<?php endif ?>">
  <input type="hidden" value="<?= $this->escapeHtmlAttr($id) ?>" class="hiddenId"/>
  <input type="hidden" value="<?= $this->escapeHtmlAttr($source) ?>" class="hiddenSource"/>
  <?=$this->record($this->driver)->getCheckbox()?>
  <div class="media">
    <?php if ($thumbnail && $thumbnailAlignment == 'left'): ?>
      <?= $thumbnail ?>
    <?php endif; ?>
    <div class="media-body">
      <div class="short-view">
        <div class="result-body">
          <div class="resultItemLine1">
            <?php $missing = $this->driver instanceof \VuFind\RecordDriver\Missing; ?>
            <?php if (!$missing): ?><a href="<?= $recordLinker->getUrl($this->driver)?>" class="getFull title truncate" data-view="<?= $this->params->getOptions()->getListViewOption() ?>"><?php endif; ?>
              <?= $this->record($this->driver)->getTitleHtml()?>
            <?php if (!$missing): ?></a><?php endif; ?>
          </div>

          <div class="resultItemLine2">
            <?= $this->record($this->driver)->renderTemplate('result-list-publicationDetails.phtml')?>
          </div>

          <div class="last">
            <?php if(!$this->driver->isCollection() && ($snippet = $this->driver->getHighlightedSnippet())): ?>
              <?php if (!empty($snippet['caption'])): ?>
                <strong><?= $this->transEsc($snippet['caption']); ?>:</strong>
              <?php endif; ?>

              <?php if (!empty($snippet['snippet'])): ?>
                <span class="quotestart">&#8220;</span>...<?= $this->highlight($snippet['snippet']); ?>...<span class="quoteend">&#8221;</span><br/>
              <?php endif; ?>
            <?php endif; ?>

            <div class="callnumAndLocation ajax-availability hidden">
              <?php if ($this->driver->supportsAjaxStatus()): ?>
                <strong class="hideIfDetailed"><?= $this->transEsc('Call Number')?>:</strong>
                <span class="callnumber ajax-availability hidden">
                  <?= $this->transEsc('Loading')?>...<br/>
                </span>

                <strong><?= $this->transEsc('Location_s')?>:</strong>
                <span class="location ajax-availability hidden">
                  <?= $this->transEsc('Loading')?>...
                </span>

                <div class="locationDetails"></div>
              <?php else: ?>
                <?php $summCallNo = $this->driver->getCallNumber(); if (!empty($summCallNo)): ?>
                  <strong class=""><?= $this->transEsc('Call Number')?>:</strong> <?= $this->escapeHtml($summCallNo)?>
                <?php endif; ?>
              <?php endif; ?>
            </div>

            <?php $listTags = ($this->usertags()->getMode() !== 'disabled') ? $this->driver->getTags(
                null === $list_id ? true : $list_id, // get tags for all lists if no single list is selected
                $user_id, 'tag'
               ) : array();
            ?>
            <?php if (count($listTags) > 0): ?>
              <strong><?= $this->transEsc('Your Tags')?>:</strong>
              <?php foreach ($listTags as $tag): ?>
                <a href="<?= $this->currentPath() . $results->getUrlQuery()->addFacet('tags', $tag->tag)?>"><?= $this->escapeHtml($tag->tag)?></a>
              <?php endforeach; ?>
              <br/>
            <?php endif; ?>

            <?php $listNotes = $this->driver->getListNotes($list_id, $user_id); ?>
            <?php if (count($listNotes) > 0): ?>
              <strong><?= $this->transEsc('Notes')?>:</strong>
              <?php if (count($listNotes) > 1): ?><br/><?php endif; ?>
              <?php foreach ($listNotes as $note): ?>
                <?= $this->escapeHtml($note)?><br/>
              <?php endforeach; ?>
            <?php endif; ?>

            <div class="hidden-print">
              <?php if ($this->lists && count($this->lists) > 0): ?>
                <strong><?= $this->transEsc('Saved in')?>:</strong>
                <?php $i=0;foreach($this->lists as $current): ?>
                  <a href="<?= $this->url('userList', array('id' => $current->id))?>"><?= $this->escapeHtml($current->title)?></a><?php if($i++ < count($this->lists)-1): ?>,<?php endif; ?>
                <?php endforeach; ?>
                <br/>
              <?php endif; ?>
            </div>

            <?php /* We need to find out if we're supposed to display an OpenURL link ($openUrlActive),
                  but even if we don't plan to display the link, we still want to get the $openUrl
                  value for use in generating a COinS (Z3988) tag -- see bottom of file.
                */
              $openUrl = $this->openUrl($this->driver, 'results');
              $openUrlActive = $openUrl->isActive();
              // Account for replace_other_urls setting
              $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
            ?>

            <div class="badges-row">
              <?= $this->record($this->driver)->getFormatList() ?>
              <?= $this->record($this->driver)->getOpenAccess() ?>

              <?php if (!$openUrlActive && $this->driver->supportsAjaxStatus()): ?>
                <span class="status ajax-availability hidden">
                  <span class="label label-default"><?= $this->transEsc('Loading')?>...</span>
                </span>
              <?php endif; ?>

              <?= $this->record($this->driver)->getThuringiaBibliography() ?>
            </div>

            <div class="flex-center flex-wrap action-row">
              <?= $this->record($this->driver)->renderTemplate('access-lookup.phtml'); ?>
              <?php if ($openUrlActive || !empty($urls)): ?>
                <?php if ($openUrlActive): ?>
                  <br/>
                  <?= $openUrl->renderTemplate()?>
                <?php endif; ?>
                <?php if (!is_array($urls)) $urls = array(); ?>
                <?php if(!$this->driver->isCollection()): ?>
                  <?php foreach($urls as $current): ?>
                    <?php if($current['desc'] != 'Inhaltsverzeichnis') continue; ?>
                    <a href="<?= $this->escapeHtmlAttr($this->proxyUrl($current['url']))?>" class="fulltext btn btn-primary btn-xs external-link" target="new">
                      <?= ($current['url'] == $current['desc']) ? $this->transEsc('Full text online') : $this->escapeHtml($current['desc'])?>
                    </a>
                  <?php endforeach; ?>
                <?php endif; ?>
              <?php endif; ?>

              <?= $this->record($this->driver)->getCitationReferences() ?>
            </div>

            <?= $this->record($this->driver)->getPreviews()?>
          </div>
        </div>

        <?php if ($editable) : ?>
          <div class="hidden-print edit-list-entry">
            <a href="<?= $this->url('myresearch-edit')?>?id=<?= urlencode($id)?>&amp;source=<?= urlencode($source)?><?php if (!is_null($list_id)):?>&amp;list_id=<?= urlencode($list_id)?><?php endif; ?>" class="edit tool"><i class="fa fa-fw fa-edit" aria-hidden="true"></i> <?= $this->transEsc('Edit')?></a><br/>
            <?php /* Use a different delete URL if we're removing from a specific list or the overall favorites: */
              $deleteUrl = null === $list_id
                  ? $this->url('myresearch-favorites')
                  : $this->url('userList', array('id' => $list_id));
              $deleteUrlGet = $deleteUrl . '?delete=' . urlencode($id) . '&amp;source=' . urlencode($source);

              $dLabel = 'delete-label-' . preg_replace('[\W]','-',$id);
            ?>
            <div class="dropdown">
              <a class="dropdown-toggle" id="<?= $dLabel ?>" role="button" data-toggle="dropdown" href="<?= $deleteUrlGet ?>">
                <i class="fa fa-fw fa-trash-o" aria-hidden="true"></i> <?= $this->transEsc('Delete') ?>
              </a>
              <ul class="dropdown-menu" role="menu" aria-labelledby="<?= $dLabel ?>">
                <li><a onClick="$.post('<?= $deleteUrl?>', {'delete':'<?= $this->escapeJs($id) ?>','source':'<?= $this->escapeJs($source) ?>','confirm':true},function(){location.reload(true)})" title="<?= $this->transEscAttr('confirm_delete_brief')?>"><?= $this->transEsc('confirm_dialog_yes')?></a></li>
                <li><a><?= $this->transEsc('confirm_dialog_no')?></a></li>
              </ul>
            </div>

            <?= $this->driver->supportsCoinsOpenUrl()?'<span class="Z3988" title="'.$this->escapeHtmlAttr($this->driver->getCoinsOpenUrl()).'"></span>':''?>
          </div>
        <?php endif; ?>
      </div>
    </div>

    <?php if ($thumbnail && $thumbnailAlignment == 'right'): ?>
      <?= $thumbnail ?>
    <?php endif; ?>
  </div>
</div>
