<?php if($this->gnd): ?>
  <span>
    <a href="#_" data-toggle="popover" data-placement="top" data-trigger="focus" data-html="true" title="<?= $this->transEsc('search in'); ?>"><?= $this->escapeHtml($this->desc); ?></a>
    <div class="hidden">
      <div class="popover-link-list">
        <div>
          <a href="<?= $this->record($this->driver)->getLink('author', $this->desc) ?>" target="_blank"><?= $this->transEsc('library_search_name'); ?> (Fuzzy)</a>
        </div>

        <div>
          <a href="<?= $this->record($this->driver)->getLink($this->linkType, "{$this->gnd} ({$this->desc})") ?>" target="_blank"><?= $this->transEsc('library_search_name'); ?> (Normdaten)</a>
        </div>

        <h3 class="popover-title"><?= $this->transEsc('open in'); ?></h3>
        <?php foreach($this->thulb_normlink()->getLinksForGND($this->gnd) as $link): ?>
          <div>
            <img src="<?=$link['icon']?>" alt="<?= $this->transEscAttr($link['name']); ?>" />
            <a href="<?= $link['url']; ?>" target="_blank"><?= $this->transEsc($link['name']); ?></a>
          </div>
        <?php endforeach; ?>
      </div>
    </div>
  </span>
<?php else: ?>
  <a href="<?= $this->record($this->driver)->getLink('author', $this->desc) ?>" target="_blank"><?= $this->transEsc($this->desc); ?></a>
<?php endif; ?>
