<?= $this->inlineScript(\Laminas\View\Helper\HeadScript::FILE, 'onlinecontent.js', 'SET');?>

<div class="ajax-online-content flex-center center-text">
  <img src="/themes/thulb/images/Ajax-loader.gif" class="online-content-loading hidden">
  <span class="online-content online-content" data-online-content="<?= $this->escapeHtml($this->driver->getSourceIdentifier() . ':' . $this->driver->getUniqueID())?>">
  </span>
</div>