<?php
  $citesCount = $this->driver->tryMethod('getCitatedReferencesCount');
  $citesLink = $this->driver->tryMethod('getCitatedReferencesLink');
?>
<?php if ($citesCount) :?>
  <span class="speech-bubble html-tooltip" title="<?= $this->translate('Web of Science Scites Tooltip')?>">
    <?php if ($citesLink):?>
      <a href="<?= $citesLink?>" target="_blank"><?= $citesCount?></a>
    <?php else: ?>
      <?= $citesCount?>
    <?php endif; ?>
  </span>
<?php endif;?>
