<?php
  $truncateSettings = [
    'rows' => $this->config()->getRecordSubjectLimit(),
      'btn-class' => 'btn-link p-0',
//      'in-place-toggle': false,
//      'label': null,
      'less-icon' => '',
//      'less-label': VuFind.translate('less_ellipsis'),
      'more-icon' => '',
//      'more-label': VuFind.translate('more_ellipsis'),
//      'rows': 3,
//      'top-toggle': Infinity,
//      'wrapper-class': '', // '' will glean from element, false or null will exclude a class
//      'wrapper-tagname': null, // falsey values will glean from element
//      'label-icons': 'before' // 'after' = icon after label, 'before' = icon before label, false = no icons
  ];
?>
<div class="truncate-subjects" data-truncate="<?=$this->htmlSafeJsonEncode($truncateSettings)?>">
  <?php foreach ($data as $key => $field): ?>
    <div class="subject-line"<?=$this->schemaOrg()->getAttributes(['property' => 'keywords'])?>>
      <?php
        $subject = '';
        if (count($field) == 1) {
          $field = explode('--', $field[0]);
        }
        $i = 0;
        $total = count($field);
      ?>
      <?php foreach ($field as $subfield): ?>
        <?=($i++ == 0) ? '' : ' &gt; '?>
        <?php $subject = trim($subject . ' ' . $subfield); ?>
        <a title="<?=$this->escapeHtmlAttr($subject)?>" href="<?=$this->record($this->driver)->getLink('subject', $subject)?>" rel="nofollow"><?=trim($this->escapeHtml($subfield))?></a>
      <?php endforeach; ?>
    </div>
  <?php endforeach; ?>
</div>
