<?php foreach ($data as $key => $field): ?>
  <?php if ($key > 0): ?>
    <br>
  <?php endif; ?>

  <?php /* Depending on the record driver, $field may either be an array with
     "name" and "number" keys or a flat string containing only the series
     name.  We should account for both cases to maximize compatibility. */ ?>
  <?php if (is_array($field)): ?>
    <?php if (!empty($field['name'])): ?>
      <?php if (isset($field['id']) && $field['id']) : ?>
        <?php $url = $this->recordLinker()->related(['type' => 'bib', 'value' => $field['id']]); ?>
        <a href="<?=$url?>" target="_blank"><?= $this->escapeHtml($field['name'])?></a>
      <?php else: ?>
        <?=$this->escapeHtml($field['name'])?>
      <?php endif; ?>

      <?php if (!empty($field['number'])): ?>
        <?=$this->escapeHtml($field['number'])?>
      <?php endif; ?>
    <?php endif; ?>
  <?php else: ?>
    <a href="<?=$this->record($this->driver)->getLink('series', $field)?>" target="_blank"><?=$this->escapeHtml($field)?></a>
  <?php endif; ?>
<?php endforeach; ?>
