<?php
  // Set up some convenience variables:
  $id = $this->driver->getUniqueId();
  $source = $this->driver->getSourceIdentifier();
  if (isset($this->list) && is_object($this->list)) {
    $list_id = $this->list->getId();
    $user_id = $this->list->getUser()->getId();
  }
  else {
    $list_id = null;
    $user_id = $this->user ? $this->user->id : null;
  }
  $editable = $this->user && $user_id === $this->user->id;

  // Thumbnail
  $coverDetails = $this->record($this->driver)->getCoverDetails('list-entry', 'medium', $this->recordLinker()->getUrl($this->driver));
  $cover = $coverDetails['html'];
  $thumbnail = false;
  $thumbnailAlignment = $this->record($this->driver)->getThumbnailAlignment('list');
?>
<li class="result<?php if ($this->driver->supportsAjaxStatus()): ?> ajaxItem<?php endif ?>">
  <?php if ($cover):
    ob_start(); ?>
    <div class="hidden-xs media-<?=$thumbnailAlignment ?> <?=$this->escapeHtmlAttr($coverDetails['size'])?>">
      <?=$cover ?>
    </div>
    <?php $thumbnail = ob_get_contents(); ?>
    <?php ob_end_clean(); ?>
  <?php endif; ?>

  <input type="hidden" value="<?=$this->escapeHtmlAttr($id) ?>" class="hiddenId">
  <input type="hidden" value="<?=$this->escapeHtmlAttr($source) ?>" class="hiddenSource">
  <?=$this->record($this->driver)->getCheckbox()?>

  <div class="media">
    <?php if ($thumbnail && $thumbnailAlignment == 'left'): ?>
      <?=$thumbnail ?>
    <?php endif; ?>

    <div class="media-body d-flex flex-wrap flex-sm-nowrap gap-4">
      <div class="result-body flex-grow-1">
        <h2>
          <?php $missing = $this->driver instanceof \VuFind\RecordDriver\Missing; ?>
          <?php if (!$missing): ?><a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($this->driver))?>" class="truncate getFull" data-view="<?=$this->params->getOptions()->getListViewOption() ?>"><?php endif; ?>
            <span class="title"><?=$this->record($this->driver)->getTitleHtml()?></span>
          <?php if (!$missing): ?></a><?php endif; ?>
          <?php foreach ($this->driver->tryMethod('getTitlesAltScript', [], []) as $altTitle): ?>
            <div class="title-alt">
              <?=$this->escapeHtml($altTitle)?>
            </div>
          <?php endforeach; ?>
        </h2>

        <div class="resultItemLine1">
          <?php if (!$this->driver->isCollection()): ?>
            <?php $summAuthors = $this->driver->getPrimaryAuthors(); ?>
            <?php if (!empty($summAuthors)): ?>
              <span class="authors">
                <?=$this->transEsc('by')?>:
                <?php $authorCount = count($summAuthors); ?>
                <?php foreach ($summAuthors as $i => $summAuthor): ?>
                  <?=$this->escapeHtml($summAuthor)?><?=($i + 1 < $authorCount ? ';' : '') ?>
                <?php endforeach; ?>
              </span>
            <?php endif; ?>
          <?php endif; ?>
        </div>

        <div class="resultItemLine2">
          <?php if ($this->driver->isCollection()): ?>
            <?=implode('<br>', array_map([$this, 'escapeHtml'], $this->driver->getSummary())); ?>
          <?php else: ?>
            <?php
              $journalTitle = $this->driver->getContainerTitle();
              $summDate = $this->driver->getPublicationDates();
              $journalRef = $this->driver->getContainerReference();
            ?>
            <?php if (!empty($journalTitle)): ?>
              <?=$this->transEsc('Published in')?>:
              <?= $this->highlight($journalTitle) ?><?= ($journalRef) ? ', ' . $journalRef : ''?>
            <?php endif; ?>

            <?php $summInCollection = $this->driver->getContainingCollections(); ?>
            <?php if (!empty($summInCollection)): ?>
              <?php foreach ($summInCollection as $collId => $collText): ?>
                <div>
                  <b><?=$this->transEsc('in_collection_label')?></b>
                  <a class="collectionLinkText" href="<?=$this->record($this->driver)->getLink('collection', $collId)?>">
                    <?=$this->escapeHtml($collText)?>
                  </a>
                </div>
              <?php endforeach; ?>
            <?php endif; ?>
          <?php endif; ?>
        </div>

        <div class="last">
          <?php if(!$this->driver->isCollection()): ?>
            <?php if($snippet = $this->driver->getHighlightedSnippet()): ?>
              <?php if (!empty($snippet['caption'])): ?>
                <strong><?= $this->transEsc($snippet['caption']); ?>:</strong>
              <?php endif; ?>

              <?php if (!empty($snippet['snippet'])): ?>
                <span class="quotestart">&#8220;</span>...<?= $this->highlight($snippet['snippet']); ?>...<span class="quoteend">&#8221;</span><br/>
              <?php endif; ?>
            <?php endif; ?>
          <?php endif; ?>

          <?php
            $listTags = ($this->usertags()->getMode() !== 'disabled') ? $this->record($this->driver)->getTagsFromFavorites(
              $list_id,
              $user_id,
              'tag'
            ) : [];
          ?>
          <?php if (count($listTags) > 0): ?>
            <strong><?=$this->transEsc('Your Tags')?>:</strong>
            <?php foreach ($listTags as $tag): ?>
              <a href="<?=$this->currentPath() . $results->getUrlQuery()->addFacet('tags', $tag['tag'])?>"><?=$this->escapeHtml($tag['tag'])?></a>
            <?php endforeach; ?>
            <br>
          <?php endif; ?>

          <?php $listNotes = $this->record($this->driver)->getListNotes($list_id, $user_id); ?>
          <?php if (count($listNotes) > 0): ?>
            <strong><?=$this->transEsc('Notes')?>:</strong>
            <?php if (count($listNotes) > 1): ?><br><?php endif; ?>
            <?php foreach ($listNotes as $note): ?>
              <?=$this->escapeHtml($note)?><br>
            <?php endforeach; ?>
          <?php endif; ?>

          <div class="callnumAndLocation ajax-availability hidden">
            <?php if ($this->driver->supportsAjaxStatus()): ?>
              <span class="location ajax-availability hidden">
                <?=$this->icon('spinner')?>
                <?=$this->transEsc('loading_ellipsis')?>
              </span>
              <ul class="locationDetails"></ul>
            <?php else: ?>
              <?php $summCallNo = $this->driver->getCallNumber(); ?>
              <?php if (!empty($summCallNo)): ?>
                <strong><?=$this->transEsc('Call Number')?>:</strong> <?=$this->escapeHtml($summCallNo)?>
              <?php endif; ?>
            <?php endif; ?>
          </div>

          <?php if (count($this->lists ?? []) > 0): ?>
            <strong><?=$this->transEsc('Saved in')?>:</strong>
            <?php $i = 0; ?>
            <?php foreach ($this->lists as $current): ?>
              <a href="<?=$this->url('userList', ['id' => $current->getId()])?>"><?=$this->escapeHtml($current->getTitle())?></a><?php if ($i++ < count($this->lists) - 1): ?>,<?php endif; ?>
            <?php endforeach; ?>
            <br>
          <?php endif; ?>

          <?php
            /* We need to find out if we're supposed to display an OpenURL link ($openUrlActive),
               but even if we don't plan to display the link, we still want to get the $openUrl
               value for use in generating a COinS (Z3988) tag -- see bottom of file.
             */
            $openUrl = $this->openUrl($this->driver, 'results');
            $openUrlActive = $openUrl->isActive();
            $doi = $this->doi($this->driver, 'results');
            $doiActive = $doi->isActive();
            // Account for replace_other_urls setting
            $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
          ?>

          <div class="badges-row">
            <?= $this->record($this->driver)->getFormatList() ?>
            <?= $this->record($this->driver)->getOpenAccess() ?>

            <?php if (!$openUrlActive && $this->driver->supportsAjaxStatus()): ?>
              <span class="status ajax-availability hidden"><?=$this->transEsc('loading_ellipsis')?></span>
            <?php endif; ?>

            <?= $this->record($this->driver)->getThuringiaBibliography() ?>
          </div>

          <div class="d-flex flex-wrap gap-2 align-items-center action-row hidden-print">
            <?=$this->record($this->driver)->renderTemplate('access-lookup.phtml'); ?>

            <?php if ($openUrlActive): ?>
              <?=$openUrl->renderTemplate()?>
            <?php endif; ?>

            <?php if ($doiActive): ?>
              <?=$doi->renderTemplate()?>
            <?php endif; ?>

            <?php $urls = is_array($urls) ? $urls : []; ?>
            <?php if (!$this->driver->isCollection()): ?>
              <?php foreach ($urls as $current): ?>
                <?php if($current['desc'] != 'Inhaltsverzeichnis') continue; ?>
                <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>" class="fulltext btn btn-primary btn-sm" target="new">
                  <span class="icon-link__label"><?= ($current['url'] == $current['desc']) ? $this->transEsc('Full text online') : $this->transEsc($current['desc'])?></span>
                  <?=$this->icon('external-link', 'icon-link__icon') ?>
                </a>
              <?php endforeach; ?>
            <?php endif; ?>

            <?php if ($this->searchOptions($this->driver->getSourceIdentifier())->displayCitationLinksInResults()): ?>
              <?php if($citationReferencesHtml = $this->record($this->driver)->getCitationReferences()): ?>
                <?= $citationReferencesHtml; ?>
              <?php elseif($links = $this->driver->tryMethod('getCitations')): ?>
                <div class="result-citation-links">
                  <?=$this->record($this->driver)->renderTemplate('data-citations.phtml', ['data' => $links])?>
                </div>
              <?php endif; ?>
            <?php endif; ?>
          </div>

          <?=$this->record($this->driver)->getPreviews()?>
        </div>
      </div>

      <div class="result-links hidden-print d-flex flex-column">
        <a href="<?=$this->url('myresearch-edit')?>?id=<?=urlencode($id)?>&amp;source=<?=urlencode($source)?><?php if (null !== $list_id):?>&amp;list_id=<?=urlencode($list_id)?><?php endif; ?>" class="edit tool icon-link">
          <?=$this->icon('user-list-entry-edit', 'icon-link__icon') ?>
          <span class="icon-link__label"><?=$this->transEsc('Edit')?></span>
        </a>

        <?php /* Use a different delete URL if we're removing from a specific list or the overall favorites: */
          $deleteUrl = null === $list_id
              ? $this->url('myresearch-favorites')
              : $this->url('userList', ['id' => $list_id]);
          $deleteUrlGet = $deleteUrl . '?delete=' . urlencode($id) . '&amp;source=' . urlencode($source);
          $md5Id = md5($id);
        ?>
        <?=
          $this->component(
            'confirm-button',
            [
              'buttonClass' => 'btn-link',
              'buttonLink' => $deleteUrlGet,
              'buttonIcon' => 'user-list-remove',
              'buttonLabel' => 'Delete',
              'confirmId' => 'confirm_delete_item_' . $md5Id,
            ]
          )
        ?>

        <?=$this->driver->supportsCoinsOpenUrl()?'<span class="Z3988" title="'.$this->escapeHtmlAttr($this->driver->getCoinsOpenUrl()).'"></span>':''?>
      </div>
    </div>

    <?php if ($thumbnail && $thumbnailAlignment == 'right'): ?>
      <?=$thumbnail ?>
    <?php endif; ?>
  </div>

  <?php
    $escId = $this->escapeJs($id);
    $escSource = $this->escapeJs($source);
    $script = <<<JS
      $('#confirm_delete_item_{$md5Id}').click(function(e) {
        e.preventDefault();
        $.post('${deleteUrl}', {
            'delete':'${escId}',
            'source':'${escSource}',
            'confirm':true
          },
          function() {
            location.reload()
          }
        );
      });
    JS;
  ?>
  <?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET');?>
</li>
