<?php $normLink = $this->thulb_normlink(); ?>
<?php if ($this->gnd && $normLink->isEnabled()): ?>
  <span>
    <a href="#" id="popover-<?=$this->gnd?>" title="<?= $this->transEsc('Search Options'); ?>" tabindex="0" data-bs-toggle="popover" data-bs-placement="top" data-bs-trigger="click" data-bs-html="true" data-bs-delay='{"show":0,"hide":100}' data-bs-container="#popover-<?=$this->gnd?>-container" aria-expanded="false" role="button"><?= $this->desc; ?></a>
    <span id="popover-<?=$this->gnd?>-container"></span>
  </span>
  <div class="hidden" id="popover-<?=$this->gnd?>-content">
    <div class="popover-link-list">
      <a href="<?= $this->record($this->driver)->getLink('author', $this->desc) ?>" target="_blank"><?= $this->transEsc('search_text'); ?></a>
      <a href="<?= $this->record($this->driver)->getLink($this->linkType, "{$this->gnd}") ?>" target="_blank"><?= $this->transEsc('search_authority_data'); ?></a>

      <h3 class="popover-header"><?= $this->transEsc('Further content in'); ?></h3>
        <?php foreach ($normLink->getLinksForGND($this->gnd) as $link): ?>
          <a href="<?= $link['url']; ?>" target="_blank">
            <span class="imgWrapper">
              <img src="<?=$link['icon']?>" alt="<?= $this->transEscAttr($link['name']); ?>" />
            </span>
              <?= $this->transEsc($link['name']); ?>
          </a>
        <?php endforeach; ?>
    </div>
  </div>
<?php else: ?>
  <a href="<?= $this->record($this->driver)->getLink('author', $this->desc) ?>" target="_blank"><?= $this->transEsc($this->desc); ?></a>
<?php endif; ?>
