<?php $normLink = $this->thulb_normlink(); ?>
<?php if ($this->gnd && $normLink->isEnabled()): ?>
  <span>
    <a href="#_" tabindex="0" data-bs-toggle="popover" data-bs-placement="top" data-bs-trigger="focus" data-bs-html="true" title="<?= $this->transEsc('Search Options'); ?>"><?= $this->desc; ?></a>
    <div class="hidden">
      <div class="popover-link-list">
        <a href="<?= $this->record($this->driver)->getLink('author', $this->desc) ?>" target="_blank"><?= $this->transEsc('search_text'); ?></a>
        <a href="<?= $this->record($this->driver)->getLink($this->linkType, "{$this->gnd}") ?>" target="_blank"><?= $this->transEsc('search_authority_data'); ?></a>

        <h3 class="popover-header"><?= $this->transEsc('Further content in'); ?></h3>
        <?php foreach ($normLink->getLinksForGND($this->gnd) as $link): ?>
          <a href="<?= $link['url']; ?>" target="_blank">
            <span class="imgWrapper">
              <img src="<?=$link['icon']?>" alt="<?= $this->transEscAttr($link['name']); ?>" />
            </span>
            <?= $this->transEsc($link['name']); ?>
          </a>
        <?php endforeach; ?>
      </div>
    </div>
  </span>
<?php else: ?>
  <a href="<?= $this->record($this->driver)->getLink('author', $this->desc) ?>" target="_blank"><?= $this->transEsc($this->desc); ?></a>
<?php endif; ?>
