<?=$this->flashmessages()?>

<div>
  <h2><?=$this->transEsc('Report problems accessing e-resources')?></h2>

  <form class="form-horizontal authority-form" method="post" name="authority">
    <div class="d-flex flex-column mb-3 gap-4">
      <fieldset class="flex-grow-1">
        <legend class="mb-0"><?=$this->transEsc('Do you want feedback')?></legend>
        <div class="form-check">
          <input class="form-check-input" value="true" type="radio" name="feedback" id="feedback-yes" required>
          <label class="form-check-label" for="feedback-yes"><?=$this->transEsc('Yes')?></label>
        </div>
        <div class="form-check">
          <input class="form-check-input" value="false" type="radio" name="feedback" id="feedback-no" required>
          <label class="form-check-label" for="feedback-no"><?=$this->transEsc('No')?></label>
        </div>
      </fieldset>

      <div class="broken-link-feedback-info d-flex flex-column mb-3 gap-4">
        <div class="flex-grow-1">
          <label for="firstname" class="font-weight-bold mb-2"><?=$this->transEsc('First Name')?></label>
          <input id="firstname" type="text" name="firstname" class="form-control flex-grow-1" placeholder="<?= $this->transEsc('First Name'); ?>" value="<?=$this->escapeHtmlAttr($this->firstname)?>" />
        </div>
        <div class="flex-grow-1">
          <label for="lastname" class="font-weight-bold mb-2"><?=$this->transEsc('Last Name')?></label>
          <input id="lastname" type="text" name="lastname" class="form-control flex-grow-1" placeholder="<?= $this->transEsc('Last Name'); ?>" value="<?=$this->escapeHtmlAttr($this->lastname)?>" />
        </div>
        <div class="flex-grow-1">
          <label for="email" class="font-weight-bold mb-2"><?=$this->transEsc('E-Mail')?></label>
          <input id="email" type="email" name="email" class="form-control flex-grow-1" placeholder="<?= $this->transEsc('E-Mail'); ?>" value="<?=$this->escapeHtmlAttr($this->email)?>" />
        </div>
      </div>
    </div>

    <div class="center-text mb-2">
      <button class="btn btn-primary"><?=$this->transEsc('Report problem')?></button>
    </div>
  </form>
</div>