<ul class="nav navbar-nav navbar-left">
  <li><a href="https://www.dhge.de/DHGE/Hochschule/Anfahrt_und_Kontakt.html" target="_blank"><?= $this->transEsc("Header_contact")?></a></li>
  <li><a href="https://kataloge.thulb.uni-jena.de/DB=5/LNG=DU/" target="_blank"><?= $this->transEsc('Katalog Eisenach')?></a></li>
  <li><a href="https://kataloge.thulb.uni-jena.de/DB=4/LNG=DU/" target="_blank"><?= $this->transEsc('Katalog Gera')?></a></li>
  <li><a href="https://kxp.k10plus.de/DB=2.1/DB=2.1/LNG=DU/" target="_blank"><?= $this->transEsc('Header_interlibrary_loan')?></a></li>
</ul>
