<ul class="nav navbar-nav navbar-left">
  <li><a href="http://www.thulb.uni-jena.de/ThULBSuche" target="_blank"><?= $this->transEsc('Header_new')?></a></li>
  <li><a href="http://www.thulb.uni-jena.de/A+_+Z/Suchtipps.html" target="_blank"><?= $this->transEsc('Header_searchtipps')?></a></li>
  <li><a href="https://www.dhge.de/DHGE/Hochschule/Anfahrt_und_Kontakt.html" target="_blank"><?= $this->transEsc("Header_contact")?></a></li>
  <li><a href="https://kataloge.thulb.uni-jena.de/DB=5/LNG=DU/" target="_blank"><?= $this->transEsc('Katalog Eisenach')?></a></li>
  <li><a href="https://kataloge.thulb.uni-jena.de/DB=4/LNG=DU/" target="_blank"><?= $this->transEsc('Katalog Gera')?></a></li>
</ul>
