<div class="collapse navbar-collapse" id="tsnavbar">
  <ul class="nav navbar-nav">
    <?php if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
      <li class="language dropdown visible-xs">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <?= strtoupper($this->layout()->userLang); ?> <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <?php foreach ($this->layout()->allLangs as $langCode => $langName): ?>
            <li  class="langOption<?= $this->layout()->userLang == $langCode ? ' active' : ''?>"><a href="#" onClick="document.langForm.mylang.value='<?= $langCode?>';document.langForm.submit()"><?= $this->displayLanguageOption($langName)?></a></li>
          <?php endforeach; ?>
        </ul>
      </li>
    <?php endif; ?>
    <li><a href="http://www.thulb.uni-jena.de/ThULBSuche" target="_blank"><?= $this->transEsc('Header_new')?></a></li>
    <li><a href="http://www.thulb.uni-jena.de/A+_+Z/Suchtipps.html" target="_blank"><?= $this->transEsc('Header_searchtipps')?></a></li>
    <li><a href="http://www.thulb.uni-jena.de/Mailformulare/Discovery.html" target="_blank"><?= $this->transEsc("Header_contact")?></a></li>
    <li class="visible-xs"><a href="https://www.thulb.uni-jena.de/impressum.html" target="_blank"><?= $this->transEsc('Footer_imprint')?></a></li>
    <li><a href="https://kataloge.thulb.uni-jena.de/DB=1/LNG=DU/" target="_blank"><?= $this->transEsc('Header_catalog')?></a></li>
    <li class="dropdown">
      <a href="https://kxp.k10plus.de/DB=2.1/DB=2.1/LNG=DU/" class="dropdown-toggle" data-toggle="dropdown" target="_blank"><?= $this->transEsc('Interlibrary loan')?> <b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><a href="https://fernleihe.thulb.uni-jena.de/login" target="_blank"><?= $this->translate('Recharge credit, Forgot password')?></a></li>
        <li><a href="https://kxp.k10plus.de/login/LNG=DU/LOGIN/REQUEST?DB=2.1" target="_blank"><?= $this->transEsc('Login GVK')?></a></li>
        <li><a href="https://kxp.k10plus.de/DB=2.1/DB=2.1/LNG=DU/" target="_blank"><?= $this->transEsc('Order in GVK')?></a></li>
        <li><a href="https://www.thulb.uni-jena.de/fernleihe.html" target="_blank"><?= $this->transEsc('Further information')?></a></li>
      </ul>
    </li>
  </ul>
</div>