<ul class="nav navbar-nav navbar-left">
  <li><a href="http://www.thulb.uni-jena.de/ThULBSuche" target="_blank"><?= $this->transEsc('Header_new')?></a></li>
  <li><a href="http://www.thulb.uni-jena.de/A+_+Z/Suchtipps.html" target="_blank"><?= $this->transEsc('Header_searchtipps')?></a></li>
  <li><a href="http://www.thulb.uni-jena.de/Mailformulare/Discovery.html" target="_blank"><?= $this->transEsc("Header_contact")?></a></li>
  <li class="visible-xs"><a href="https://www.thulb.uni-jena.de/impressum.html" target="_blank"><?= $this->transEsc('Footer_imprint')?></a></li>
  <li><a href="http://kataloge.thulb.uni-jena.de" target="_blank"><?= $this->transEsc('Header_catalog')?></a></li>
</ul>
