<ul class="navbar-tips nav navbar-nav">
  <?php if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
    <?=$this->component('menu-button', [
      'toggleLabel' => strtoupper($this->layout()->userLang) . ' ',
      'wrapperClass' => 'language visible-xs',
      'wrapperTag' => 'li',
      'href' => '#_',
      'menuItems' => array_map(
        function ($langCode, $langName) {
          return [
            'label' => $this->displayLanguageOption($langName),
            'url' => $this->url()->addQueryParameters(['lng' => $langCode]),
            'selected' => $this->layout()->userLang == $langCode,
          ];
        },
        array_keys($this->layout()->allLangs),
        array_values($this->layout()->allLangs),
      ),
    ]) ?>
  <?php endif; ?>

  <li class="dropdown">
    <a href="#_" class="dropdown-toggle arrow-down" data-toggle="dropdown"><?= $this->transEsc('Header_searchtipps')?></a>
    <ul class="dropdown-menu">
      <li><a href="<?= $this->translate('URL::Search tips'); ?>" target="_blank"><?= $this->transEsc('ThULB-FAQ')?></a></li>
      <li><a href="<?= $this->translate('URL::Tutorial_Useraccount'); ?>" target="_blank"><?= $this->transEsc(  'Tutorial Useraccount')?></a></li>
      <li><a href="<?= $this->translate('URL::Tutorial_Favorite_List'); ?>" target="_blank"><?= $this->transEsc('Tutorial favorite lists')?></a></li>
      <li><a href="<?= $this->translate('URL::help_advanced_search'); ?>" target="_blank"><?= $this->transEsc('Help - advanced search')?></a></li>
      <li><a href="<?= $this->translate('URL::help_search_operators'); ?>" target="_blank"><?= $this->transEsc('Help - search operators')?></a></li>
    </ul>
  </li>

  <li class="dropdown">
    <a href="#_" class="dropdown-toggle arrow-down" data-toggle="dropdown"><?= $this->transEsc('Found nothing')?></b></a>
    <ul class="dropdown-menu">
      <li><a href="<?= $this->translate('URL::DBIS'); ?>" target="_blank"><?= $this->transEsc('Databases DBIS')?></a></li>

      <li class="dropdown dropdown-submenu">
        <a href="#_" class="dropdown-toggle arrow-right arrow-down-sm" data-toggle="dropdown"><?= $this->transEsc('E-Journals / E-Newspapers')?></a>
        <ul class="dropdown-menu">
          <li><a href="<?= $this->translate('URL::EZB'); ?>" target="_blank"><?= $this->transEsc('Electronic journal library EZB')?></a></li>
          <li><a href="<?= $this->translate('URL::WISO'); ?>" target="_blank"><?= $this->translate('Daily and weekly newspapers WISO')?></a></li>
          <li><a href="<?= $this->translate('URL::Libkey'); ?>" target="_blank"><?= $this->transEsc('DOI quick search')?></a></li>
          <li><a href="<?= $this->translate('URL::BrowZine'); ?>" target="_blank"><?= $this->transEsc('BrowZine')?></a></li>
        </ul>
      </li>

      <li><a href="<?= $this->thulb_serviceDesk('acquisition-suggestion'); ?>" target="_blank"><?= $this->transEsc('Acquisition suggestion')?></a></li>

      <li><a href="<?= $this->translate('URL::OPAC'); ?>" target="_blank"><?= $this->transEsc('OPAC')?></a></li>

      <li class="dropdown dropdown-submenu">
        <a href="#_" class="dropdown-toggle arrow-right arrow-down-sm" data-toggle="dropdown"><?= $this->transEsc('Digital Collections Thuringia')?></a>
        <ul class="dropdown-menu">
          <li><a href="<?= $this->translate('URL::UrMEL_Collections'); ?>" target="_blank"><?= $this->transEsc('Prints, manuscripts and bequests')?></a></li>
          <li><a href="<?= $this->translate('URL::UrMEL_Journals'); ?>" target="_blank"><?= $this->translate('Journals and Newspapers')?></a></li>
          <li><a href="<?= $this->translate('URL::DBT'); ?>" target="_blank"><?= $this->transEsc('E-publications and university publications')?></a></li>
          <li><a href="<?= $this->translate('URL::Kulthura'); ?>" target="_blank"><?= $this->transEsc("Kulthura")?></a></li>
        </ul>
      </li>

      <li><a href="<?= $this->translate('URL::university_bibliography_jena'); ?>" target="_blank"><?= $this->transEsc('University bibliography jena')?></a></li>

      <li><a href="<?= $this->translate('URL::Subject information'); ?>" target="_blank"><?= $this->transEsc('Subject information')?></a></li>
    </ul>
  </li>

  <li class="dropdown">
    <a href="#_" class="dropdown-toggle arrow-down" data-toggle="dropdown"><?= $this->transEsc('Interlibrary loan')?> </a>
    <ul class="dropdown-menu">
      <li><a href="<?= $this->translate('URL::Order in GVK'); ?>" target="_blank"><?= $this->transEsc('Order in GVK')?></a></li>
      <li><a href="<?= $this->url('ill-chargecredits'); ?>"><?= $this->translate('Recharge credit, Forgot password')?></a></li>
      <li><a href="<?= $this->translate('URL::Login GVK'); ?>" target="_blank"><?= $this->transEsc('Login GVK')?></a></li>
      <li><a href="<?= $this->translate('URL::ILL information'); ?>" target="_blank"><?= $this->transEsc('ILL information')?></a></li>
    </ul>
  </li>

  <li class="dropdown">
    <a href="#_" class="dropdown-toggle arrow-down" data-toggle="dropdown"><?= $this->transEsc("Header_contact")?></a>
    <ul class="dropdown-menu">
      <li><a href="<?= $this->thulb_serviceDesk('information-services', ['topic' => '20009']); ?>" target="_blank"><?= $this->transEsc('Header_general_questions'); ?></a> </li>
      <li><a href="<?= $this->thulb_serviceDesk('borrow-services'); ?>" target="_blank"><?= $this->transEsc("Header_account_lending")?></a></li>
      <li><a href="<?= $this->thulb_serviceDesk('broken-link'); ?>" target="_blank"><?= $this->transEsc('Header_access_problem'); ?></a> </li>
    </ul>
  </li>
</ul>
