<?php $loginMethod = $this->auth()->getManager()->getILSLoginMethod(); ?>
<?php if ('email' === $loginMethod): ?>
  <div class="form-group">
    <label class="control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_username"><?=$this->transEsc('Email')?>:</label>
    <input type="text" name="username" id="login_<?=$this->escapeHtmlAttr($topClass)?>_username" value="<?=$this->escapeHtmlAttr($this->request->get('username'))?>" class="form-control" autocomplete="username">
  </div>
<?php else: ?>
  <div class="form-group">
    <label><?= $this->transEsc('Campus'); ?>:</label><br>
    <input type="radio" name="library" id="login_Gera" value="Gera">
    <label class="control-label" for="login_Gera">Gera</label><br>
    <input type="radio" name="library" id="login_Eisenach" value="Eisenach">
    <label for="login_Eisenach">Eisenach</label><br>
  </div>

  <div class="form-group">
    <label class="control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_username"><?=$this->transEsc('Username')?>:</label>
    <input type="text" name="username" id="login_<?=$this->escapeHtmlAttr($topClass)?>_username" value="<?=$this->escapeHtmlAttr($this->request->get('username'))?>" class="form-control" autocomplete="username" placeholder="<?= $this->transEscAttr('login_user_input_hint'); ?>">
  </div>

  <div class="form-group">
    <label class="control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_password"><?=$this->transEsc('Password')?>:</label>
    <input type="password" name="password" id="login_<?=$this->escapeHtmlAttr($topClass)?>_password" class="form-control" autocomplete="current-password" placeholder="<?= $this->transEscAttr('login_password_input_hint'); ?>">
  </div>
<?php endif; ?>