<?php
  // Set page title.
  $this->headTitle($this->translate('Search Home'));

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $config = $this->config()->get('config');
    $this->searchClassId = $config->Site->defaultSearchBackend ?? 'Solr';
  }

  $this->layout()->breadcrumbs = false;
?>

<?=$this->flashmessages()?>

<div class="searchHomeContent hidden-xs">
  <?php $this->slot('search-home-hero')->start() ?>

  <?php
    $ilsStatusScript = <<<JS
      $(document).ready(function() {
        $.ajax({
          dataType: 'json',
          method: 'GET',
          data: {'offlineModeMsg':'ils_offline_home_message'},
          url: VuFind.path + '/AJAX/JSON?method=getIlsStatus',
          success: function(response) {
            $('.searchHomeContent').append(response.data);
          }
        });
        $("#searchForm_lookfor").focus();
      });
    JS;
  ?>
  <?= $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $ilsStatusScript, 'SET'); ?>

  <?=$this->slot('search-home-hero')->end() ?>
</div>