<?php if ($this->pageCount > 1): ?>
  <?php
    $showFirstLast = $this->pageCount > 3 && $this->results->getOptions()->firstLastNavigationSupported();
    $navAttrs = $this->htmlAttributes(['aria-label' => $this->translate('pagination_label')]);
    if ($this->results->getOptions()->loadResultsWithJsEnabled()) {
      $navAttrs->add('class', 'js-pagination');
      if ($this->top) {
        $navAttrs->add('class', 'js-pagination__top');
      }
    }
  ?>
  <nav<?=$navAttrs?>>
    <?php
      $ulAttrs = $this->htmlAttributes(['class' => 'pagination flex-wrap']);
      if ($this->top) {
        $ulAttrs->add('class', 'pagination-top');
      }
      if ($className = $this->options['className'] ?? '') {
        $ulAttrs->add('class', $className);
      }
    ?>
    <ul<?=$ulAttrs?>>
      <?php if (isset($this->previous)): ?>
        <?php if ($showFirstLast): ?>
          <?=
            $this->render(
              'Helpers/pagination-item.phtml',
              [
                'results' => $this->results,
                'current' => $this->current,
                'page' => 1,
                'liClasses' => ['page-first'],
                'label' => $this->translate('page_first'),
                'contentHtml' => '[1]',
                'ajaxTab' => $this->ajaxTab ?? false,
              ]
            )
          ?>
        <?php endif; ?>

        <?=
          $this->render(
            'Helpers/pagination-item.phtml',
            [
              'results' => $this->results,
              'current' => $this->current,
              'page' => $this->previous,
              'liClasses' => ['page-prev'],
              'label' => $this->translate('page_prev'),
              'contentHtml' => $this->icon('page-prev', 'align-baseline'),
              'ajaxTab' => $this->ajaxTab ?? false,
            ]
          )
        ?>
      <?php endif; ?>

      <?php if (count($this->pagesInRange) > 1): ?>
        <?php foreach ($this->pagesInRange as $page): ?>
          <?=
            $this->render(
              'Helpers/pagination-item.phtml',
              [
                'results' => $this->results,
                'current' => $this->current,
                'page' => $page,
                'label' => $this->translate('page_num', ['%%page%%' => $page]),
                'contentHtml' => $this->escapeHtml($page),
                'ajaxTab' => $this->ajaxTab ?? false,
              ]
            )
          ?>
        <?php endforeach; ?>
      <?php endif; ?>

      <?php if (isset($this->next)): ?>
        <?=
          $this->render(
            'Helpers/pagination-item.phtml',
            [
              'results' => $this->results,
              'current' => $this->current,
              'page' => $this->next,
              'liClasses' => ['page-next'],
              'label' => $this->translate('page_next'),
              'contentHtml' => $this->icon('page-next', 'align-baseline'),
              'ajaxTab' => $this->ajaxTab ?? false,
            ]
          )
        ?>
        <?php if ($showFirstLast): ?>
          <?=
            $this->render(
              'Helpers/pagination-item.phtml',
              [
                'results' => $this->results,
                'current' => $this->current,
                'page' => $this->last,
                'liClasses' => ['page-last'],
                'label' => $this->translate('page_last'),
                'contentHtml' => '[' . $this->escapeHtml($this->pageCount) . ']',
                'ajaxTab' => $this->ajaxTab ?? false,
              ]
            )
          ?>
        <?php endif; ?>
      <?php endif; ?>
    </ul>
  </nav>
<?php endif; ?>
