<?php
    // Initialize from current search (if available and not explicitly overridden) or defaults:
    if ($results = ($this->results ?? $this->searchMemory()->getCurrentSearch())) {
      $params = $results->getParams();
      $this->searchClassId ??= $params->getSearchClassId();
    }
    else {
      $params = null;
      $this->searchClassId ??= $this->config()->get('config')->Site->defaultSearchBackend
        ?? 'Solr';
    }
    // Initialize from current search if eligible, defaults otherwise:
    if (isset($params) && $this->searchClassId === $params->getSearchClassId()) {
      $hiddenFilters = $params->getHiddenFilters();
      $lastSort = $params->getSort();
      $lastLimit = $params->getLimit();
      $options = $params->getOptions();
    }
    else {
      $hiddenFilters = $this->searchTabs()->getHiddenFilters($this->searchClassId, $this->ignoreHiddenFilterMemory ?? false, $this->ignoreHiddenFiltersInRequest ?? false);
      $lastSort = $this->searchMemory()->getLastSort($this->searchClassId);
      $lastLimit = $this->searchMemory()->getLastLimit($this->searchClassId);
      $options = $this->searchOptions($this->searchClassId);
    }
    // Override search class ID with searchbox-specific settings, if necessary:
    $overrideSearchClassId = $options->getSearchBoxSearchClassId();
    if ($overrideSearchClassId !== $this->searchClassId) {
      $this->searchClassId = $overrideSearchClassId;
      $options = $this->searchOptions($overrideSearchClassId);
    }

    // Load search actions and settings (if any):
    $keyboardLayouts = $this->searchbox()->getKeyboardLayouts();
    $handlers = $this->searchbox()->getHandlers(
      $this->searchClassId,
      $this->searchIndex ?? null
    );
    $handlerCount = count($handlers);
    $basicSearch = $this->searchbox()->combinedHandlersActive() ? 'combined-searchbox' : $options->getSearchAction();
    $searchHome = $options->getSearchHomeAction();
    $advSearch = $options->getAdvancedSearchAction();

    $filterList = is_array($this->filterList) ? $this->filterList : [];
    $checkboxFilters = is_array($this->checkboxFilters) ? $this->checkboxFilters : [];
    $filterDetails = $this->searchbox()->getFilterDetails($filterList, $checkboxFilters);
    $showFilters = $filterDetails && ($results || $options->getRetainFilterSetting());
?>
<?php $tabConfig = $this->searchTabs()->getTabConfig($this->searchClassId, $this->lookfor, $this->searchIndex, $this->searchType, $hiddenFilters); ?>
<?php if ($this->searchType == 'advanced'): ?>
  <div class="navbar-form navbar-left flip">
    <?php if (!empty($tabs)): ?><?=$tabs ?><div class="tab-content clearfix"><?php endif; ?>
      <div id="results-adv-search-header" class="d-flex justify-content-between flex-wrap flex-sm-nowrap gap-4">
        <p class="adv_search_terms mb-0">
          <?=$this->transEsc('Your search terms')?>: "<strong><?=$this->escapeHtml($this->lookfor)?></strong>"
        </p>

        <div class="d-flex flex-column align-items-end col-12 col-sm-auto">
          <a href="#_" id="results-adv-search-edit" class="btn btn-primary text-nowrap col-12 col-sm-auto collapsed" data-bs-toggle="collapse" data-bs-target="#results-adv-search"><span class="results-adv-search-edit-text"><?=$this->transEsc('Edit search')?></span> <?=$this->icon('collapse')?></a>
          <a href="<?=$this->url($searchHome, [], ['query' => $hiddenFilters])?>" class="basic-search-link mt-2">&raquo; <?=$this->transEsc('Basic Search')?></a>
        </div>
      </div>

      <div id="results-adv-search" class="collapse">
        <?= $this->context()->renderInContext('search/advanced/layout.phtml', [
          'options' => $options,
          'saved' => $results,
          'overrideHeadTitle' => false
        ]); ?>
      </div>

      <?=
        $this->context($this)->renderInContext(
          'search/filters.phtml',
          [
            'params' => $params ?? null,
            'urlQuery' => isset($results) ? $results->getUrlQuery() : null,
            'filterList' => $showFilters ? $filterList : [],
            'checkboxFilters' => $showFilters ? $checkboxFilters : [],
            'searchClassId' => $this->searchClassId,
            'searchType' => $this->searchType,
          ]
        );
      ?>
    <?php if (!empty($tabs)): ?></div><?php endif; ?>
  </div>
<?php else: ?>
  <div class="keyboard-box">
    <div class="simple-keyboard"></div>
  </div>
  <form id="searchForm" class="searchForm navbar-form navbar-left flip" method="get" action="<?=$this->url($basicSearch)?>" name="searchForm" autocomplete="off">
    <div class="searchForm-inputs d-flex flex-column flex-sm-row">
      <?php
        // Note: we need type="text" for autocomplete role="combobox"
        $searchboxAttributes = [
          'id' => 'searchForm_lookfor',
          'class' => 'searchForm_lookfor form-control form-control-lg search-query',
          'type' => 'text',
          'name' => 'lookfor',
          'value' => $this->lookfor,
          'aria-label' => $this->translate('search_terms'),
        ];
        if ($placeholder = $this->searchbox()->getPlaceholderText($tabConfig['selected']['id'] ?? $this->searchClassId)) {
          $searchboxAttributes['placeholder'] = $this->translate($placeholder);
        }
        if ($this->searchbox()->autocompleteEnabled($this->searchClassId)) {
          $searchboxAttributes['class'] .= " autocomplete searcher:{$this->searchClassId}"
              . ($this->searchbox()->autocompleteAutoSubmit($this->searchClassId) ? ' ac-auto-submit' : '');
          $searchboxAttributes['data-autocomplete-formatting-rules'] = $this->searchbox()->autocompleteFormattingRulesJson($this->searchClassId);
        }
        if (!empty($keyboardLayouts)) {
          $searchboxAttributes['class'] .= ' with-keyboard-selection';
        }
      ?>
      <div class="searchForm-query">
        <input<?=$this->htmlAttributes($searchboxAttributes)?>>
        <div id="searchForm_controls">
          <button id="searchForm-reset" class="searchForm-reset hidden" type="reset" tabindex="-1" aria-label="<?=$this->transEscAttr('searchform_reset_button')?>"><?=$this->icon('ui-reset-search');?></button>
          <?php if (!empty($keyboardLayouts)): ?>
            <?php
              $this->headScript()->appendFile('vendor/js.cookie.js');
              $this->headScript()->appendFile('vendor/simple-keyboard/index.js');
              $this->headScript()->appendFile('vendor/simple-keyboard-layouts/index.js');
              $this->headLink()->appendStylesheet('vendor/simple-keyboard/index.css');
            ?>
            <div class="keyboard-selection dropdown">
              <button class="btn btn-primary dropdown-toggle" type="button" id="keyboard-selection-button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <?=$this->icon('keyboard-o') ?>
                <?=$this->icon('caret-down') ?>
              </button>

              <ul class="dropdown-menu" aria-labelledby="keyboard-selection-button">
                <li>
                  <a class="dropdown-item keyboard-selection-item" href="#" data-value="none"><?= $this->transEsc('None') ?></a>
                </li>
                <?php foreach ($keyboardLayouts as $keyboardLayout): ?>
                  <li>
                    <a class="keyboard-selection-item" href="#" data-value="<?= $this->escapeHtmlAttr($keyboardLayout) ?>"><?= $this->transEsc("KeyboardLayout::$keyboardLayout") ?></a>
                  </li>
                <?php endforeach; ?>
              </ul>
            </div>
          <?php endif; ?>
        </div>
      </div>

      <?php if ($handlerCount > 1): ?>
        <select id="searchForm_type" class="searchForm_type form-control-lg order-sm-first" name="type" data-native-menu="false" aria-label="<?=$this->transEscAttr('Search type')?>">
          <?php $currentGroup = $insideGroup = false; ?>
          <?php foreach ($handlers as $handler): ?>
            <?php
              if ($currentGroup !== ($handler['group'] ?? false)) {
                $currentGroup = $handler['group'];
                if ($insideGroup) {
                  echo '</optgroup>';
                }
                if ($currentGroup) {
                  echo '<optgroup label="' . $this->escapeHtmlAttr($currentGroup) . '">';
                  $insideGroup = true;
                }
                else {
                  $insideGroup = false;
                }
              }
            ?>
            <option value="<?=$this->escapeHtmlAttr($handler['value'])?>"<?=$handler['selected'] ? ' selected="selected"' : ''?>><?=$handler['indent'] ? '-- ' : ''?><?=$this->transEsc($handler['label'])?></option>
          <?php endforeach; ?>
          <?php if ($insideGroup): ?>
            </optgroup>
          <?php endif; ?>
        </select>
      <?php elseif ($handlerCount == 1): ?>
        <input type="hidden" name="type" value="<?=$this->escapeHtmlAttr($handlers[0]['value'])?>">
      <?php endif; ?>

      <button type="submit" class="btn btn-primary form-control-lg" title="<?= $this->transEscAttr("Find")?>"><?=$this->icon('search', 'icon-link__icon fs-5') ?></button>

      <?php if ($geoUrl = $this->geocoords()->getSearchUrl($options)) : ?>
        <a href="<?=$geoUrl ?>" class="btn btn-link"><?=$this->transEsc('Geographic Search')?></a>
      <?php endif; ?>

      <?php $shards = $options->getShards(); ?>
      <?php if ($options->showShardCheckboxes() && !empty($shards)): ?>
        <?php
          $selectedShards = $this->selectedShards ?? $options->getDefaultSelectedShards();
        ?>
        <br>
        <?php foreach ($shards as $shard => $val): ?>
          <?php $isSelected = empty($selectedShards) || in_array($shard, $selectedShards); ?>
          <input type="checkbox" <?=$isSelected ? 'checked="checked" ' : ''?>name="shard[]" value='<?=$this->escapeHtmlAttr($shard)?>'> <?=$this->transEsc($shard)?>
        <?php endforeach; ?>
      <?php endif; ?>

      <?php if (($hasDefaultsApplied ?? false) || !empty($filterDetails)): ?>
        <?php if ($options->getRetainFilterSetting()): ?>
          <?php foreach ($filterDetails as $current): ?>
            <input class="applied-filter" id="<?=$this->escapeHtmlAttr($current['id'])?>" type="hidden" name="filter[]" value="<?=$this->escapeHtmlAttr($current['value'])?>">
          <?php endforeach; ?>

          <?php if ($hasDefaultsApplied ?? false): ?>
            <input class="applied-filter" id="dfApplied" type="hidden" name="dfApplied" value="1">
          <?php endif; ?>
        <?php endif; ?>
      <?php endif; ?>

      <?php foreach ($hiddenFilters as $key => $filter): ?>
        <?php foreach ($filter as $value): ?>
          <input type="hidden" name="hiddenFilters[]" value="<?=$this->escapeHtmlAttr($key) . ':' . $this->escapeHtmlAttr('"' . $value . '"')?>">
        <?php endforeach; ?>
      <?php endforeach; ?>

      <?php
        /* Show hidden field for active search class when in combined handler mode. */
        if ($this->searchbox()->combinedHandlersActive()) {
          echo '<input type="hidden" name="activeSearchClassId" value="' . $this->escapeHtmlAttr($this->searchClassId) . '">';
        }
        /* Load hidden limit preference from Session */
        if (!empty($lastLimit)) {
          echo '<input type="hidden" name="limit" value="' . $this->escapeHtmlAttr($lastLimit) . '">';
        }
        if (!empty($lastSort) && $lastSort !== $params?->getDefaultSort()) {
          echo '<input type="hidden" name="sort" value="' . $this->escapeHtmlAttr($lastSort) . '">';
        }
      ?>
    </div>

    <div class="col-12 d-flex justify-content-end">
      <?php if ($advSearch): ?>
        <?php $advSearchLink = $this->url($advSearch, [], ['query' => $hiddenFilters]); ?>
        <a href="<?=$advSearchLink?>" class="advanced-search-link mt-2" rel="nofollow">&raquo; <?=$this->transEsc('Advanced Search');?></a>
      <?php endif; ?>
    </div>

    <?=$this->context($this)->renderInContext(
      'search/filters.phtml',
      [
        'params' => $params ?? null,
        'urlQuery' => isset($results) ? $results->getUrlQuery() : null,
        'filterList' => $showFilters ? $filterList : [],
        'checkboxFilters' => $showFilters ? $checkboxFilters : [],
        'searchClassId' => $this->searchClassId,
        'searchType' => $this->searchType,
        'showOnMobile' => false
      ]
    );?>
  </form>
<?php endif; ?>
