<?php
  $this->layout()->searchbox = false;

  $german = $this->german;
  $english = $this->english;
  $tags = $this->tags;
?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <div class="tag-information">
    <span>Information:</span> Zeilenumbrüche die durch die Enter-Taste eingefügt wurden werden automatisch in HTML-Zeilenumbrüche umgewandelt.
    Zudem werden alle HTML-Tags, außer dem &lt;a&gt;-Tag, automatisch aus dem Text entfernt.
  </div>

  <?php echo $this->flashmessages(); ?>

  <form action="<?=$this->url('DynMessages-save')?>" method="post">
    <table>
      <thead>
        <tr>
          <th class="tag-col"><?= $this->transEsc('Information'); ?></th>
          <th class="text-col"><?= $this->transEsc('Languages::German'); ?></th>
          <th class="text-col"><?= $this->transEsc('Languages::English'); ?></th>
        </tr>
      </thead>
      <tbody>
      <?php foreach($tags as $tag => $content): ?>
        <?php if(!array_key_exists($tag, $german) || !array_key_exists($tag, $english)) continue; ?>
        <tr>
          <td class="tag-col">
            <?php echo $content; ?>
          </td>
          <td class="text-col de">
            <textarea class="text-input" rows=5 name="german[<?php echo $tag; ?>]"><?php echo $german[$tag]; ?></textarea>
          </td>
          <td class="text-col en">
            <textarea class="text-input" rows=5 name="english[<?php echo $tag; ?>]"><?php echo $english[$tag]; ?></textarea>
          </td>
        </tr>
      <?php endforeach; ?>
        <tr>
          <td>&nbsp;</td>
          <td>
            <input type="submit" value="<?= $this->transEsc('Save'); ?>" class="btn btn-primary" />
            <a id="preview" class="ml-2"><?= $this->transEsc('Preview'); ?></a>
          </td>
        </tr>
      </tbody>
    </table>
  </form>

  <div id="dynmessage-preview-container">
    <h3>Vorschau DE:</h3>
    <?= $this->render('Helpers/dynamic_message.phtml', ['tag' => 'dynmessage-preview-de', 'message' => '&nbsp;']); ?>
    <h3>Vorschau EN:</h3>
    <?= $this->render('Helpers/dynamic_message.phtml', ['tag' => 'dynmessage-preview-en', 'message' => '&nbsp;']); ?>
  </div>

  <script>
    $('#preview').click(function(event){
      event.preventDefault();

      var de = $('td.text-col.de textarea').val();
      var en = $('td.text-col.en textarea').val();

      if(de !== "" || en !== "") {
        $('#dynmessage-preview-de div').html(formatPreview(de));
        $('#dynmessage-preview-en div').html(formatPreview(en));

        $('#dynmessage-preview-container div').show();
        $('#dynmessage-preview-container').show();
      }
    });

    function formatPreview(str) {
      str = (str + '').trim();

      // Replace normal linebreaks with BR-tags
      // from https://stackoverflow.com/a/2919363
      str = str.replace(/([^>\r\n]?)(\r\n|\n\r|\r|\n)/g, '$1<br>$2');

      // Remove all HTML-tags except whitelisted ones
      // original from https://stackoverflow.com/a/5601929
      var whitelist = "a, i, strong, em, br";
      var el = $('<div />');
      el.html(str);

      $(el).children().not(whitelist).each(function() {
        var content = $(this).contents();
        $(this).replaceWith(content);
      });

      return el.html();
    }
  </script>
</div>

<div class="<?=$this->layoutClass('sidebar')?>">
    <?=$this->render("admin/menu.phtml")?>
</div>