<?php if (isset($list)): ?>
  <input type="hidden" name="listID" value="<?=$this->escapeHtmlAttr($list->getId())?>">
  <input type="hidden" name="listName" value="<?=$this->escapeHtmlAttr($list->getTitle())?>">
<?php endif; ?>
<?php $user = $this->auth()->getUserObject(); ?>

<div class="cart-controls flex-center hidden-print">
  <div class="checkbox pull-left flip">
    <label class="flex-center center-text">
      <input type="checkbox" name="selectAll" class="checkbox-select-all"/>
      <span><?= $this->transEsc('select_page')?></span>
    </label>
  </div>

  <div class="item-count">
    <?php $recordTotal = $this->results->getResultTotal(); ?>
    <?php if ($recordTotal > 0): ?>
      <?php
        $transParams = [
          '%%start%%' => $this->localizedNumber($this->results->getStartRecord()),
          '%%end%%' => $this->localizedNumber($this->results->getEndRecord()),
          '%%total%%' => $this->localizedNumber($recordTotal)
        ];
      ?>
      <?= $this->translate('showing_items_of_html', $transParams); ?>
    <?php endif; ?>
  </div>

  <div class="btn-group pull-left flip">
    <a class="btn btn-thulb visible-xxs dropdown-toggle" data-toggle="dropdown"><i class="fa fa-ellipsis-v" aria-hidden="true"></i></a>
    <div class="dropdown-menu dropdown-menu-right" id="list-actions">
      <?= $this->bulkAction()->button('email', 'send-email', 'bulk_email_myresearch', [
        'title' => $this->translate('bulk_email_myresearch'),
      ]) ?>

      <?php if ((null !== $this->list && $this->list->editAllowed($user)) || null === $this->list && $user): ?>
        <button class="btn btn-thulb flex-center-xs ml-auto" id="<?= $this->idPrefix?>delete_list_items_<?= !is_null($this->list) ? $this->escapeHtmlAttr($this->list->id) : ''?>" type="submit" name="delete" value="<?= $this->transEscAttr('Delete')?>" title="<?= $this->transEscAttr('delete_selected')?>">
          <span class="visible-xxs ws-nowrap mr-2"><?= $this->transEscAttr('delete_selected')?></span>
          <i class="fa fa-trash" aria-hidden="true"></i>
        </button>
        <?= $this->bulkAction()->button('delete', 'ui-delete', 'bulk_delete_myresearch', [
          'id' => $this->idPrefix . 'delete_list_items_' . (null !== $this->list ? $this->escapeHtmlAttr($this->list->getId()) : ''),
          'title' => $this->translate('bulk_delete_myresearch'),
        ]) ?>
      <?php endif; ?>

      <?php $exportOptions = $this->export()->getActiveFormats('bulk'); if (count($exportOptions) > 0): ?>
        <?= $this->bulkAction()->button('export', 'export', 'bulk_export_myresearch', [
          'title' => $this->translate('bulk_export_myresearch'),
        ]) ?>
      <?php endif; ?>

      <?= $this->bulkAction()->button('print', 'print', 'bulk_print_myresearch', [
        'title' => $this->translate('bulk_print_myresearch'),
        'data-lightbox-ignore' => '',
      ]) ?>

      <?php if ($this->cart()->isActive()): ?>
        <?= $this->bulkAction()->button('add', 'cart-add', 'Add to Book Bag', [
          'id' => $this->idPrefix . 'updateCart',
          'title' => $this->translate('Add to Book Bag'),
        ]) ?>
      <?php endif; ?>
    </div>
  </div>
</div>
