<?php
  $user = $this->auth()->getUserObject();
?>
<?=$this->component('hide-offcanvas-button')?>
<h4 id="acc-menu-acc-header"><?= $this->transEsc('Your Account')?></h4>
<nav class="myresearch-menu" aria-labelledby="acc-menu-acc-header">
  <ul class="account-menu">
    <?php foreach ($this->items as $item): ?>
      <?=$this->render('myresearch/menu-item.phtml', ['active' => $this->active, ...$item])?>
    <?php endforeach; ?>
  </ul>
</nav>

<?php if($user && $this->config()->get('thulb')->ILL->enabled): ?>
  <h4 id="acc-menu-ill-header"><?= $this->transEsc('My Interlibrary loan')?></h4>
  <nav class="myresearch-menu" aria-labelledby="acc-menu-ill-header">
    <a href="<?= $this->url('ill-chargecredits')?>" class="<?= $this->active == 'chargecredits' ? ' active' : ''?>">
      <i class="fa fa-fw fa-book" aria-hidden="true"></i> <?= $this->transEsc('ill_credits_charge')?>
    </a>
    <a href="<?= $this->url('ill-forgotpassword')?>" class="<?= $this->active == 'forgotillpassword' ? ' active' : ''?>">
      <i class="fa fa-fw fa-book" aria-hidden="true"></i> <?= $this->transEsc('ill_forgot_password')?>
    </a>
    <a href="<?= $this->url('ill-deleteaccount')?>" class="<?= $this->active == 'deleteaccount' ? ' active' : ''?>">
      <i class="fa fa-fw fa-book" aria-hidden="true"></i> <?= $this->transEsc('ill_delete_account')?>
    </a>
  </nav>
<?php endif; ?>

<?php if ($user && $this->userlist()->getMode() !== 'disabled'): ?>
  <h4 id="acc-menu-lists-header"><?= $this->transEsc('Your Lists')?></h4>
  <nav class="myresearch-menu" aria-labelledby="acc-menu-lists-header">
    <ul>
      <?php
        // Use a variable so that we can output this nicely without whitespace that would get underlined:
        $publicInd = $this->icon(
            'user-public-list-indicator',
            [
              'class' => 'user-list__public-icon',
              'title' => $this->transEscAttr('public_list_indicator'),
            ]
        );
        $publicInd .= '<span class="sr-only">(' . $this->transEsc('public_list_indicator') . ')</span>';
      ?>

      <?php if ($this->accountCapabilities()->getSavedSearchSetting() === 'enabled'): ?>
        <li>
          <a href="<?= $this->url('search-history')?>?require_login" class="<?= $this->active == 'history' ? ' active' : ''?>">
            <?=$this->icon('cart-add', 'icon-link__icon') ?> <?= $this->transEsc('history_saved_searches_tab')?>
          </a>
        </li>
      <?php endif; ?>

      <li>
        <a href="<?= $this->url('myresearch-favorites')?>" class="<?= $this->active == 'favorites' ? ' active' : ''?>">
          <?=$this->icon('cart-add', 'icon-link__icon') ?> <?= $this->transEsc('saved_items')?>
        </a>
      </li>

      <?php $lists = $user->getLists() ?>
      <?php foreach ($lists as $list): ?>
        <li>
          <a class="user-list-link icon-link <?=$this->active == 'list' . $list->getId() ? ' active' : ''?>" href="<?=$this->url('userList', ['id' => $list->getId()])?>">
            <span class="icon-link__label"><?=$this->escapeHtml($list->getTitle())?></span>
            <?=$list->isPublic() ? $publicInd : ''?>
            <span class="badge"><?=$list->cnt ?></span>
          </a>
        </li>
      <?php endforeach; ?>
      <li>
        <a href="<?=$this->url('editList', ['id' => 'NEW'])?>" class="icon-link <?=$this->active == 'editlist/NEW' ? ' active' : ''?>">
          <?=$this->icon('cart-add', 'icon-link__icon') ?>
          <span class="icon-link__label"><?=$this->transEsc('Create a List') ?></span>
        </a>
      </li>
    </ul>
  </nav>
<?php endif ?>
